/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.40                      *
*        Compiled Mar 17 2017, 15:34:36                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: FontSong26.c                                          *
* Font:        ËÎÌå                                                  *
* Height:      26                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  26                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: D:\¿ÎÉè\emwin×ÖÌå\1.txt                         *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFontSong26;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_002F[ 44] = { /* code 002F, SOLIDUS */
  ________,__X_____,
  ________,_X______,
  ________,_X______,
  ________,XX______,
  ________,X_______,
  _______X,X_______,
  _______X,________,
  _______X,________,
  ______X_,________,
  ______X_,________,
  _____X__,________,
  _____X__,________,
  ____X___,________,
  ____X___,________,
  ___X____,________,
  ___X____,________,
  __XX____,________,
  __X_____,________,
  _XX_____,________,
  _X______,________,
  _X______,________,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0030[ 36] = { /* code 0030, DIGIT ZERO */
  ____XXXX,________,
  __XX___X,X_______,
  __X_____,XX______,
  _XX_____,XX______,
  _XX_____,_X______,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  _XX_____,_X______,
  _XX_____,XX______,
  __X_____,XX______,
  __XX___X,X_______,
  ____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0031[ 18] = { /* code 0031, DIGIT ONE */
  ____X___,
  ___XX___,
  XXXXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0032[ 36] = { /* code 0032, DIGIT TWO */
  ___XXXXX,________,
  _XX____X,X_______,
  X_______,XX______,
  X_______,XX______,
  XX______,XX______,
  XX______,XX______,
  ________,XX______,
  _______X,X_______,
  ______XX,________,
  ______X_,________,
  _____X__,________,
  ____X___,________,
  ___X____,________,
  __X_____,_X______,
  _XX_____,_X______,
  XX______,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0033[ 36] = { /* code 0033, DIGIT THREE */
  __XXXX__,________,
  _X___XX_,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  ______XX,________,
  ______X_,________,
  _____XX_,________,
  ___XXX__,________,
  _____XX_,________,
  ______XX,________,
  _______X,X_______,
  _______X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,________,
  _X____XX,________,
  __XXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0034[ 36] = { /* code 0034, DIGIT FOUR */
  ______XX,________,
  ______XX,________,
  _____XXX,________,
  _____XXX,________,
  ____X_XX,________,
  ____X_XX,________,
  ___X__XX,________,
  __X___XX,________,
  __X___XX,________,
  _X____XX,________,
  _X____XX,________,
  X_____XX,________,
  XXXXXXXX,XXX_____,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ___XXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0035[ 36] = { /* code 0035, DIGIT FIVE */
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  _X______,________,
  _X______,________,
  _X______,________,
  _X______,________,
  _X_XXXX_,________,
  _XX___XX,________,
  _X____XX,________,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  X_____XX,________,
  _X____XX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0036[ 36] = { /* code 0036, DIGIT SIX */
  ____XXXX,X_______,
  ___XX___,XX______,
  __X_____,XX______,
  _XX_____,________,
  _X______,________,
  XX______,________,
  XX______,________,
  XX__XXXX,X_______,
  XX_X____,XX______,
  XXX_____,XX______,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  _XX_____,_XX_____,
  _XX_____,XX______,
  __XX____,XX______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0037[ 36] = { /* code 0037, DIGIT SEVEN */
  _XXXXXXX,X_______,
  XXXXXXXX,X_______,
  XX_____X,________,
  X______X,________,
  X_____X_,________,
  ______X_,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0038[ 36] = { /* code 0038, DIGIT EIGHT */
  __XXXXXX,________,
  _XX____X,X_______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  _XX_____,X_______,
  __XXX__X,________,
  ___XXXX_,________,
  __X__XXX,________,
  _XX____X,X_______,
  XX_____X,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  _XX_____,XX______,
  _XX____X,X_______,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0039[ 36] = { /* code 0039, DIGIT NINE */
  ___XXXXX,________,
  _XXX___X,X_______,
  _XX_____,XX______,
  XX______,_X______,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XXX_____,XXX_____,
  _XXX___X,_XX_____,
  __XXXXX_,_XX_____,
  ________,_XX_____,
  ________,XX______,
  ________,XX______,
  _XX_____,XX______,
  _XX____X,X_______,
  _XX___XX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0041[ 36] = { /* code 0041, LATIN CAPITAL LETTER A */
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  ____X_XX,________,
  ____X_XX,________,
  ____X__X,________,
  ____X__X,________,
  ___X___X,X_______,
  ___X___X,X_______,
  ___X____,X_______,
  ___XXXXX,X_______,
  __X_____,X_______,
  __X_____,XX______,
  __X_____,XX______,
  __X_____,_X______,
  _X______,_X______,
  _XX_____,_XX_____,
  XXXX____,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0042[ 36] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXXXXX,________,
  _XX____X,X_______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX____X,X_______,
  _XXXXXXX,________,
  _XX____X,X_______,
  _XX_____,XX______,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,XXX_____,
  _XX____X,XX______,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0043[ 36] = { /* code 0043, LATIN CAPITAL LETTER C */
  ____XXXX,________,
  ___XX___,XX______,
  __XX____,_XX_____,
  _XX_____,__X_____,
  _XX_____,__X_____,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  _X______,__X_____,
  _XX_____,__X_____,
  _XX_____,_X______,
  __XX____,X_______,
  ____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0044[ 36] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXXXXX,________,
  __XX___X,X_______,
  __XX____,_X______,
  __XX____,_XX_____,
  __XX____,__X_____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,XX______,
  __XX___X,X_______,
  XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0045[ 36] = { /* code 0045, LATIN CAPITAL LETTER E */
  _XXXXXXX,XXX_____,
  __XX____,_XX_____,
  __XX____,___X____,
  __XX____,___X____,
  __XX____,________,
  __XX____,X_______,
  __XX____,X_______,
  __XX____,X_______,
  __XXXXXX,X_______,
  __XX____,X_______,
  __XX____,X_______,
  __XX____,X_______,
  __XX____,________,
  __XX____,___X____,
  __XX____,___X____,
  __XX____,__X_____,
  __XX____,_XX_____,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0046[ 36] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXXXXX,XXX_____,
  __XX____,_XX_____,
  __XX____,___X____,
  __XX____,___X____,
  __XX____,________,
  __XX____,________,
  __XX____,X_______,
  __XX____,X_______,
  __XXXXXX,X_______,
  __XX____,X_______,
  __XX____,X_______,
  __XX____,X_______,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  XXXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0047[ 36] = { /* code 0047, LATIN CAPITAL LETTER G */
  ____XXX_,________,
  ___X___X,X_______,
  __XX____,XX______,
  _XX_____,_X______,
  _XX_____,_X______,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX____XX,XXXX____,
  XX______,XX______,
  XX______,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  __X_____,XX______,
  __XX___X,XX______,
  ____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0048[ 36] = { /* code 0048, LATIN CAPITAL LETTER H */
  XXXX___X,XXX_____,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XXXXXXX,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  XXXX___X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0049[ 18] = { /* code 0049, LATIN CAPITAL LETTER I */
  XXXXXXXX,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_004A[ 42] = { /* code 004A, LATIN CAPITAL LETTER J */
  ___XXXXX,XXX_____,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  XX____XX,________,
  XX___XX_,________,
  _XXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_004B[ 36] = { /* code 004B, LATIN CAPITAL LETTER K */
  XXXXXX_X,XXX_____,
  __XX____,XX______,
  __XX___X,X_______,
  __XX___X,________,
  __XX__X_,________,
  __XX__X_,________,
  __XX_X__,________,
  __XX_XX_,________,
  __XXXXX_,________,
  __XXX_X_,________,
  __XX__XX,________,
  __XX___X,________,
  __XX___X,X_______,
  __XX____,X_______,
  __XX____,XX______,
  __XX____,XX______,
  __XX____,_XX_____,
  XXXXXX__,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_004C[ 36] = { /* code 004C, LATIN CAPITAL LETTER L */
  XXXXXX__,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,___X____,
  __XX____,___X____,
  __XX____,__XX____,
  __XX____,_XX_____,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_004D[ 36] = { /* code 004D, LATIN CAPITAL LETTER M */
  XXX_____,XXX_____,
  _XX____X,XX______,
  _XX____X,XX______,
  _XX____X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX__X_,XX______,
  _X_X__X_,XX______,
  _X_X__X_,XX______,
  _X_XX_X_,XX______,
  _X_XX_X_,XX______,
  _X_XXX__,XX______,
  _X__XX__,XX______,
  _X__XX__,XX______,
  _X__XX__,XX______,
  _X__XX__,XX______,
  _X__X___,XX______,
  XXX____X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_004E[ 36] = { /* code 004E, LATIN CAPITAL LETTER N */
  XXXX____,XXXXX___,
  __XX____,__X_____,
  __XXX___,__X_____,
  __XXX___,__X_____,
  __X_XX__,__X_____,
  __X_XX__,__X_____,
  __X__XX_,__X_____,
  __X__XX_,__X_____,
  __X___XX,__X_____,
  __X___XX,__X_____,
  __X____X,X_X_____,
  __X____X,X_X_____,
  __X____X,X_X_____,
  __X_____,XXX_____,
  __X_____,XXX_____,
  __X_____,_XX_____,
  __X_____,_XX_____,
  XXXXX___,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_004F[ 36] = { /* code 004F, LATIN CAPITAL LETTER O */
  ___XXXXX,________,
  __XX___X,X_______,
  __X_____,X_______,
  _XX_____,XX______,
  _X______,_X______,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  _X______,_X______,
  _XX_____,XX______,
  __X_____,X_______,
  __XX___X,X_______,
  ____XXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0050[ 36] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXXXXX,X_______,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,_XX_____,
  __XX____,XXX_____,
  __XXXXXX,X_______,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  XXXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0051[ 40] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ___XXXXX,________,
  __XX___X,X_______,
  _XX_____,XX______,
  _XX_____,XX______,
  _X______,_X______,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  _X_XXX__,_XX_____,
  _X_X__X_,XX______,
  _XX___XX,XX______,
  __XX__XX,X_______,
  ____XXXX,________,
  _______X,XXX_____,
  ________,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0052[ 36] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXXXXXX,X_______,
  __XX____,XX______,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,XX______,
  __XXXXXX,X_______,
  __XX__XX,________,
  __XX___X,________,
  __XX___X,X_______,
  __XX___X,X_______,
  __XX____,X_______,
  __XX____,XX______,
  __XX____,XX______,
  __XX____,_X______,
  XXXXXX__,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0053[ 36] = { /* code 0053, LATIN CAPITAL LETTER S */
  __XXXXX_,X_______,
  _XX____X,X_______,
  XX_____X,X_______,
  XX______,X_______,
  XX______,X_______,
  XX______,________,
  XXXX____,________,
  _XXXX___,________,
  __XXXXX_,________,
  ____XXXX,X_______,
  ______XX,X_______,
  _______X,XX______,
  ________,XX______,
  X_______,XX______,
  X_______,XX______,
  XX______,X_______,
  _XX____X,X_______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0054[ 36] = { /* code 0054, LATIN CAPITAL LETTER T */
  _XXXXXXX,XXX_____,
  _X___XX_,__X_____,
  X____XX_,___X____,
  X____XX_,___X____,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0055[ 36] = { /* code 0055, LATIN CAPITAL LETTER U */
  XXXX___X,XXXX____,
  _XX_____,_X______,
  _XX_____,_X______,
  _XX_____,_X______,
  _XX_____,_X______,
  _XX_____,_X______,
  _XX_____,_X______,
  _XX_____,_X______,
  _XX_____,_X______,
  _XX_____,_X______,
  _XX_____,_X______,
  _XX_____,_X______,
  _XX_____,_X______,
  _XX_____,_X______,
  _XX_____,_X______,
  _XX_____,XX______,
  __XX___X,X_______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0056[ 36] = { /* code 0056, LATIN CAPITAL LETTER V */
  XXXX____,XXXX____,
  _XX_____,__X_____,
  __X_____,_X______,
  __XX____,_X______,
  __XX____,_X______,
  __XX____,_X______,
  ___X____,X_______,
  ___XX___,X_______,
  ___XX___,X_______,
  ___XX__X,________,
  ____X__X,________,
  ____XX_X,________,
  ____XX_X,________,
  ____XXX_,________,
  _____XX_,________,
  _____XX_,________,
  _____X__,________,
  _____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0057[ 36] = { /* code 0057, LATIN CAPITAL LETTER W */
  XXXX_XXX,__XXX___,
  _XX___X_,___X____,
  _XX___X_,___X____,
  _XX___XX,___X____,
  _XX___XX,__X_____,
  __X___XX,__X_____,
  __X___XX,__X_____,
  __X__X_X,__X_____,
  __XX_X_X,__X_____,
  __XX_X_X,__X_____,
  __XX_X_X,XX______,
  ___X_X_X,XX______,
  ___XX__X,XX______,
  ___XX___,XX______,
  ___XX___,XX______,
  ___XX___,X_______,
  ___X____,X_______,
  ___X____,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0058[ 36] = { /* code 0058, LATIN CAPITAL LETTER X */
  XXXX___X,XXX_____,
  __X_____,X_______,
  __XX____,X_______,
  __XX___X,________,
  ___X___X,________,
  ___XX_X_,________,
  ____X_X_,________,
  ____XX__,________,
  _____X__,________,
  _____XX_,________,
  ____XXX_,________,
  ____X_X_,________,
  ___X__XX,________,
  ___X___X,________,
  __X____X,X_______,
  __X_____,X_______,
  _XX_____,XX______,
  XXXX___X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0059[ 36] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XXXX____,XXXX____,
  _XX_____,_XX_____,
  __X_____,_X______,
  __XX____,_X______,
  __XX____,X_______,
  ___XX___,X_______,
  ___XX__X,________,
  ____XX_X,________,
  ____XXXX,________,
  ____XXX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_005A[ 36] = { /* code 005A, LATIN CAPITAL LETTER Z */
  __XXXXXX,XXX_____,
  __XX____,_X______,
  _XX_____,XX______,
  _X______,X_______,
  _______X,X_______,
  _______X,________,
  ______XX,________,
  ______X_,________,
  _____XX_,________,
  ____XX__,________,
  ____X___,________,
  ___XX___,________,
  ___X____,________,
  __XX____,________,
  __X_____,__X_____,
  _XX_____,__X_____,
  _X______,XX______,
  XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0061[ 24] = { /* code 0061, LATIN SMALL LETTER A */
  ___XXXXX,________,
  __X____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  ______XX,X_______,
  __XXXX_X,X_______,
  _XX____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_X_____,
  XXX___XX,X_X_____,
  _XXXXX__,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0062[ 38] = { /* code 0062, LATIN SMALL LETTER B */
  ___X____,________,
  XXXX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX__XX,XX______,
  __XX_X__,_XX_____,
  __XXX___,_XX_____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,_XX_____,
  __XXX___,_XX_____,
  __X__XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0063[ 24] = { /* code 0063, LATIN SMALL LETTER C */
  ___XXXX_,________,
  __X___XX,________,
  _XX___XX,________,
  XX____XX,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,X_______,
  _XX_____,X_______,
  _XXX___X,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0064[ 38] = { /* code 0064, LATIN SMALL LETTER D */
  ________,X_______,
  _____XXX,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  __XXXX_X,X_______,
  _XX___XX,X_______,
  _XX____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  _X_____X,X_______,
  _XX___XX,XXX_____,
  __XXXX_X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0065[ 24] = { /* code 0065, LATIN SMALL LETTER E */
  ___XXXX_,________,
  __X___XX,________,
  _X_____X,________,
  XX_____X,X_______,
  XX_____X,X_______,
  XXXXXXXX,X_______,
  XX______,________,
  XX______,________,
  XX______,________,
  _XX_____,X_______,
  _XXX___X,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0066[ 36] = { /* code 0066, LATIN SMALL LETTER F */
  _____XXX,X_______,
  ____XX__,XX______,
  ___XX___,XX______,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  XXXXXXXX,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0067[ 30] = { /* code 0067, LATIN SMALL LETTER G */
  ___XXXX_,XXX_____,
  __XX__XX,_XX_____,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  __XX__XX,________,
  __XXXXX_,________,
  _XX_____,________,
  _XX_____,________,
  __XXXXXX,X_______,
  _XX____X,XX______,
  XX______,XX______,
  XX______,XX______,
  _XX____X,X_______,
  __XXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0068[ 38] = { /* code 0068, LATIN SMALL LETTER H */
  __X_____,________,
  XXX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX__XXX,X_______,
  _XX_X__X,XX______,
  _XXX____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  XXXX___X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0069[ 18] = { /* code 0069, LATIN SMALL LETTER I */
  __XXXX__,
  __XXXX__,
  ________,
  ________,
  ________,
  ____X___,
  XXXXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_006A[ 42] = { /* code 006A, LATIN SMALL LETTER J */
  _____XXX,X_______,
  _____XXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  _______X,________,
  ___XXXXX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  XX____XX,________,
  XX___XX_,________,
  _XXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_006B[ 38] = { /* code 006B, LATIN SMALL LETTER K */
  ___X____,________,
  XXXX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX___X,XXX_____,
  __XX____,X_______,
  __XX___X,________,
  __XX___X,________,
  __XX__X_,________,
  __XX_XX_,________,
  __XXX__X,________,
  __XX___X,X_______,
  __XX____,X_______,
  __XX____,XX______,
  __XX____,_XX_____,
  _XXXX___,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_006C[ 19] = { /* code 006C, LATIN SMALL LETTER L */
  ____X___,
  XXXXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_006D[ 24] = { /* code 006D, LATIN SMALL LETTER M */
  XXX_XXX_,_XXX____,
  _XXX__XX,X__XX___,
  _XX___XX,___XX___,
  _XX___XX,___XX___,
  _XX___XX,___XX___,
  _XX___XX,___XX___,
  _XX___XX,___XX___,
  _XX___XX,___XX___,
  _XX___XX,___XX___,
  _XX___XX,___XX___,
  _XX___XX,___XX___,
  XXXX_XXX,X_XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_006E[ 24] = { /* code 006E, LATIN SMALL LETTER N */
  __X__XXX,X_______,
  XXX_X__X,XX______,
  _XXX____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  XXXX___X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_006F[ 24] = { /* code 006F, LATIN SMALL LETTER O */
  ___XXXXX,________,
  __XX___X,X_______,
  _XX_____,XX______,
  _X______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  _XX_____,XX______,
  __XX___X,X_______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0070[ 30] = { /* code 0070, LATIN SMALL LETTER P */
  ___X__XX,XX______,
  XXXX_X__,_XX_____,
  __XXX___,_XX_____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,_XX_____,
  __XXX___,XXX_____,
  __XX_XXX,X_______,
  __XX____,________,
  __XX____,________,
  XXXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0071[ 30] = { /* code 0071, LATIN SMALL LETTER Q */
  ___XXXX_,_X______,
  __XX___X,XX______,
  _XX_____,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  _XX_____,XX______,
  _XX____X,XX______,
  ___XXXX_,XX______,
  ________,XX______,
  ________,XX______,
  ______XX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0072[ 24] = { /* code 0072, LATIN SMALL LETTER R */
  ___XX__X,XX______,
  XXXXX_X_,_XX_____,
  ___XXX__,_XX_____,
  ___XXX__,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0073[ 24] = { /* code 0073, LATIN SMALL LETTER S */
  __XXXX__,X_______,
  _XX___XX,X_______,
  XX______,X_______,
  XX______,X_______,
  XXX_____,________,
  _XXXXX__,________,
  ____XXXX,________,
  ______XX,X_______,
  X______X,X_______,
  X______X,X_______,
  XXX___XX,________,
  X__XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0074[ 32] = { /* code 0074, LATIN SMALL LETTER T */
  ____X___,________,
  ____X___,________,
  ___XX___,________,
  ___XX___,________,
  XXXXXXXX,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,X_______,
  ___XX___,X_______,
  ____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0075[ 26] = { /* code 0075, LATIN SMALL LETTER U */
  ___X____,__X_____,
  XXXX___X,XXX_____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XXX___,XXXXX___,
  ___XXXXX,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0076[ 24] = { /* code 0076, LATIN SMALL LETTER V */
  XXXX___X,XXX_____,
  _XX_____,XX______,
  __X_____,X_______,
  __XX____,X_______,
  ___X___X,________,
  ___X___X,________,
  ___XX__X,________,
  ____X_X_,________,
  ____XXX_,________,
  ____XXX_,________,
  _____X__,________,
  _____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0077[ 24] = { /* code 0077, LATIN SMALL LETTER W */
  XXXX_XXX,__XXX___,
  _XX___X_,___X____,
  _XX___X_,__X_____,
  __X___XX,__X_____,
  __X___XX,__X_____,
  __XX_X_X,__X_____,
  __XX_X_X,_X______,
  ___XXX_X,XX______,
  ___XX__X,XX______,
  ___XX___,XX______,
  ___XX___,X_______,
  ____X___,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_0079[ 30] = { /* code 0079, LATIN SMALL LETTER Y */
  XXXX___X,XXX_____,
  __X_____,X_______,
  __X_____,X_______,
  __XX____,X_______,
  ___X___X,________,
  ___X___X,________,
  ____X_X_,________,
  ____X_X_,________,
  ____XXX_,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  ____X___,________,
  _XX_X___,________,
  _XXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_007A[ 24] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXXXX,________,
  XX____XX,________,
  X____XX_,________,
  X____X__,________,
  ____XX__,________,
  ___XX___,________,
  ___XX___,________,
  __XX____,________,
  __X_____,X_______,
  _XX_____,X_______,
  XX_____X,X_______,
  XXXXXXXX,________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_4F4D[ 69] = { /* code 4F4D */
  ______X_,____X___,________,
  ______XX,_____X__,________,
  _____XX_,_____XX_,________,
  _____X__,______XX,________,
  _____X__,______XX,________,
  ____XX__,______X_,____X___,
  ____X__X,XXXXXXXX,XXXXXX__,
  ___XXX__,________,__XX____,
  ___XXX__,________,__XX____,
  __X_XX__,________,__XX____,
  __X_XX__,__X_____,__X_____,
  _X__XX__,__X_____,_XX_____,
  X___XX__,___X____,_XX_____,
  ____XX__,___XX___,_X______,
  ____XX__,___XX___,_X______,
  ____XX__,___XX___,_X______,
  ____XX__,____X___,X_______,
  ____XX__,________,X_______,
  ____XX__,________,X_______,
  ____XX__,_______X,_____X__,
  ____XX_X,XXXXXXXX,XXXXXXX_,
  ____XX__,________,________,
  ____X___,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_505C[ 72] = { /* code 505C */
  _____X__,_____X__,________,
  _____XX_,______X_,________,
  ____XX__,______XX,_____X__,
  ____XX_X,XXXXXXXX,XXXXXXX_,
  ____X___,________,________,
  ____X___,________,________,
  ___X____,__XXXXXX,XXXX____,
  ___XX___,__X_____,__X_____,
  __XXX___,__X_____,__X_____,
  __XXX___,__XXXXXX,XXX_____,
  _X_XX___,__X_____,__X_____,
  _X_XX__X,XXXXXXXX,XXXXXXX_,
  X__XX__X,________,_____X__,
  ___XX_XX,________,____X___,
  ___XX___,________,___X____,
  ___XX___,_XXXXXXX,XXXXX___,
  ___XX___,_______X,________,
  ___XX___,_______X,________,
  ___XX___,_______X,________,
  ___XX___,_______X,________,
  ___XX___,_______X,________,
  ___XX___,______XX,________,
  ___XX___,____XXXX,________,
  ___X____,______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_52A8[ 72] = { /* code 52A8 */
  ________,_______X,________,
  ________,_______X,X_______,
  ________,_X_____X,X_______,
  _XXXXXXX,XXX____X,X_______,
  ________,_______X,X_______,
  ________,_______X,X_______,
  ________,____XXXX,XXXXXXX_,
  ________,_______X,X____X__,
  XXXXXXXX,XXXX___X,X____X__,
  _____XX_,_______X,X____X__,
  _____XX_,_______X,X____X__,
  ____XX__,_______X,_____X__,
  ____X___,_______X,_____X__,
  ___XX___,X______X,_____X__,
  ___X____,_X_____X,_____X__,
  __X_____,_XX___XX,_____X__,
  _X_____X,XXXX__X_,_____X__,
  XXXXXXX_,__XX_XX_,_____X__,
  _XX_____,_____X__,_____X__,
  ________,____X___,____XX__,
  ________,___X____,____XX__,
  ________,__X_____,XXXXX___,
  ________,_X______,__XXX___,
  ________,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_538B[ 69] = { /* code 538B */
  ________,________,____X___,
  ____XXXX,XXXXXXXX,XXXXXX__,
  ____X___,________,________,
  ____X___,____X___,________,
  ____X___,____XXX_,________,
  ____X___,____XX__,________,
  ____X___,____XX__,________,
  ____X___,____XX__,________,
  ____X___,____XX__,________,
  ____X___,____XX__,___X____,
  ____X__X,XXXXXXXX,XXXXX___,
  ____X___,____XX__,________,
  ____X___,____XX__,________,
  ____X___,____XX__,X_______,
  ___XX___,____XX__,_X______,
  ___XX___,____XX__,_XXX____,
  ___X____,____XX__,__XX____,
  ___X____,____XX__,___X____,
  __XX____,____XX__,___X____,
  __X_____,____XX__,_____X__,
  __XXXXXX,XXXXXXXX,XXXXXXX_,
  _X______,________,________,
  X_______,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_53C2[ 69] = { /* code 53C2 */
  ________,__X_____,________,
  ________,_XXX____,________,
  ________,XX_____X,________,
  ______XX,________,XXX_____,
  ____XX__,_____XXX,XXXX____,
  ____XXXX,XXXXX___,___XX___,
  ________,_XX_____,___X____,
  ________,_XX_____,_____X__,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,X_____X_,________,
  _______X,X___X__X,________,
  ______XX,___XXX__,X_______,
  _____XX_,__XX____,_XX_____,
  ____X___,_XX_____,__XXXX__,
  __XX___X,X_____XX,____XXX_,
  _X___XX_,____XXX_,________,
  ___XX___,___XX___,__X_____,
  ________,_XX_____,XXXX____,
  ______XX,X______X,X_______,
  ___XXX__,_____XXX,________,
  ________,___XXX__,________,
  _______X,XXX_____,________,
  __XXXXX_,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_53D1[ 72] = { /* code 53D1 */
  ________,_XX_____,________,
  ____X___,_XX____X,X_______,
  ____XX__,_XX_____,XXX_____,
  ___XX___,_XX_____,_XX_____,
  ___XX___,_X______,__X_____,
  ___X____,_X______,_____X__,
  __XXXXXX,XXXXXXXX,XXXXXXX_,
  ________,XX______,________,
  ________,XX______,________,
  ________,X_______,________,
  ________,X_______,__X_____,
  _______X,XXXXXXXX,XXXX____,
  _______X,X_X_____,__X_____,
  _______X,__X_____,_XX_____,
  ______XX,___X____,XX______,
  ______XX,___X____,X_______,
  ______X_,____X__X,X_______,
  _____X__,_____XXX,________,
  ____XX__,_____XX_,________,
  ____X___,____XX_X,X_______,
  ___X____,___XX___,XXX_____,
  __X_____,_XX_____,_XXXX___,
  _X_____X,X_______,___XXXX_,
  _____XX_,________,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_5668[ 69] = { /* code 5668 */
  ________,________,________,
  ____XXXX,XX____XX,XXXX____,
  ____X___,_XX___X_,___XX___,
  ____X___,_X____X_,___X____,
  ____X___,_X____X_,___X____,
  ____X___,_X____X_,___X____,
  ____XXXX,XX____XX,XXXX____,
  ____X___,_X____XX,___X____,
  ________,__XX____,XX______,
  ________,__XX____,_X___X__,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,_X____X_,________,
  ________,X______X,________,
  ______XX,________,XX______,
  _____X__,________,__XXX___,
  ___XXXXX,XXX__XXX,XXXXXXX_,
  _XX_X___,_XX__X__,___X_X__,
  ____X___,_XX__X__,___X____,
  ____X___,_XX__X__,___X____,
  ____X___,_XX__X__,___X____,
  ____XXXX,XXX__XXX,XXXX____,
  ____X___,_XX__X__,___X____,
  ____X___,_____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_5782[ 69] = { /* code 5782 */
  ________,________,_X______,
  ________,_____XXX,XXX_____,
  _____XXX,XXXXXX__,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,____X___,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ______XX,___XX___,XX______,
  ______XX,___XX___,XX______,
  ______XX,___XX___,XX______,
  ______XX,___XX___,XX___X__,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ______XX,___XX___,XX______,
  ______XX,___XX___,XX______,
  ______XX,___XX___,XX______,
  ______XX,___XX___,XX______,
  ______XX,___XX___,XX__X___,
  _XXXXXXX,XXXXXXXX,XXXXXX__,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,____X___,
  __XXXXXX,XXXXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_5B66[ 69] = { /* code 5B66 */
  ________,________,________,
  ____X___,_XX_____,XXX_____,
  ____XX__,__XX____,XX______,
  _____XX_,__XX___X,X_______,
  _____XX_,__XX___X,________,
  ______X_,______X_,____X___,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  _XX_____,________,____XX__,
  _XX_____,________,___X____,
  XXX_____,________,__X_____,
  ___XXXXX,XXXXXXXX,X_______,
  ________,_______X,X_______,
  ________,_____XX_,________,
  ________,__X_X___,________,
  ________,___XX___,____X___,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,________,
  ______XX,__XX____,________,
  ________,XXXX____,________,
  ________,__X_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_5E45[ 72] = { /* code 5E45 */
  ___X____,________,________,
  ____X___,________,________,
  ____X___,XXXXXXXX,XXXXXX__,
  ____X___,________,________,
  ____X___,________,________,
  XXXXXXXX,X__XXXXX,XXXX____,
  X___X__X,___XX___,__XX____,
  X___X__X,___XX___,__XX____,
  X___X__X,___XX___,__XX____,
  X___X__X,___XXXXX,XXXX____,
  X___X__X,___XX___,__XX____,
  X___X__X,___X____,________,
  X___X__X,__XXXXXX,XXXXXX__,
  X___X__X,__X____X,____X___,
  X___X__X,__X____X,____X___,
  X___X__X,__X____X,____X___,
  X___XX_X,__XXXXXX,XXXXX___,
  X___X_XX,__X____X,____X___,
  ____X___,__X____X,____X___,
  ____X___,__X____X,____X___,
  ____X___,__XXXXXX,XXXXX___,
  ____X___,__X_____,____X___,
  ____X___,__X_____,____X___,
  ___XX___,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_5E73[ 69] = { /* code 5E73 */
  ________,________,____X___,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ________,___XX___,________,
  ________,___XX___,__X_____,
  _____X__,___XX___,__XX____,
  _____XX_,___XX___,_XX_____,
  ______XX,___XX___,_X______,
  ______XX,___XX___,X_______,
  _______X,___XX__X,________,
  ________,___XX_X_,_____X__,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_5EA6[ 72] = { /* code 5EA6 */
  ________,___X____,________,
  ________,____XX__,________,
  ________,____XX__,_____X__,
  ___XXXXX,XXXXXXXX,XXXXXXX_,
  ___XX___,________,________,
  ___XX___,_X______,X_______,
  ___XX___,_XX_____,XX______,
  ___XX___,_XX_____,XX______,
  ___XXXXX,XXXXXXXX,XXXXXX__,
  ___XX___,_XX_____,XX______,
  ___XX___,_XX_____,XX______,
  ___X____,_XXXXXXX,XX______,
  ___X____,_XX_____,X_______,
  ___X____,________,________,
  ___X___X,XXXXXXXX,XXX_____,
  ___X____,__X_____,_XX_____,
  __XX____,__X_____,XX______,
  __X_____,___X___X,X_______,
  __X_____,____X_XX,________,
  __X_____,_____XX_,________,
  _X______,____XXXX,________,
  _X______,__XX___X,XXX_____,
  X______X,XX______,_XXXXXX_,
  X___XXX_,________,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_5F62[ 66] = { /* code 5F62 */
  ________,_____X__,____X___,
  _XXXXXXX,XXXXXXX_,___XXX__,
  _____X__,__X_____,___X____,
  _____X__,__X_____,__X_____,
  _____X__,__X_____,_X______,
  _____X__,__X_____,X_______,
  _____X__,__X____X,________,
  _____X__,__X__XX_,____XX__,
  _XXXXXXX,XXXXXXX_,____XX__,
  _____X__,__X_____,___XX___,
  _____X__,__X_____,__X_____,
  _____X__,__X_____,_X______,
  _____X__,__X____X,X_______,
  ____XX__,__X___X_,_____XX_,
  ____XX__,__X_____,_____XXX,
  ____X___,__X_____,____XX__,
  ___XX___,__X_____,___XX___,
  ___X____,__X_____,__XX____,
  ___X____,__X_____,XX______,
  __X_____,__X____X,X_______,
  _X______,__X__XX_,________,
  X_______,____X___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_6001[ 69] = { /* code 6001 */
  ________,___X____,________,
  ________,___X____,________,
  ________,__XX____,________,
  ________,__XX____,____XX__,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,__X_X___,________,
  ________,__X__X__,________,
  ________,_XX__X__,________,
  ________,_X____X_,________,
  ________,X______X,________,
  _______X,XXX_____,XX______,
  ______X_,__XX____,_XXX____,
  ____XX__,___XX___,__XXXXXX,
  _XXX____,____X___,____XX__,
  ________,__X_____,________,
  _______X,___XX___,__X_____,
  _______X,___XXX__,___X____,
  ___X___X,____X___,___XX___,
  ___X___X,________,X___XX__,
  __XX___X,________,X___XX__,
  _XX____X,________,X____X__,
  _______X,________,XX______,
  _______X,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_626B[ 69] = { /* code 626B */
  _____X__,________,________,
  _____XX_,________,________,
  _____XX_,________,________,
  _____XX_,________,________,
  _____XX_,__XXXXXX,XXXXXXX_,
  XXXXXXXX,XX______,_____X__,
  _____XX_,________,_____X__,
  _____XX_,________,_____X__,
  _____XX_,________,_____X__,
  _____XX_,_XX_____,_____X__,
  _____XXX,X_______,_____X__,
  ____XXX_,___XXXXX,XXXXXX__,
  _XXXXXX_,________,_____X__,
  _XX__XX_,________,_____X__,
  _____XX_,________,_____X__,
  _____XX_,________,_____X__,
  _____XX_,________,_____X__,
  _____XX_,________,_____X__,
  _____XX_,________,_____X__,
  _____XX_,_XXXXXXX,XXXXXX__,
  _XXX_XX_,________,_____X__,
  ___XXX__,________,_____X__,
  ____X___,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_63CF[ 69] = { /* code 63CF */
  _____X__,________,________,
  _____XX_,_____XX_,__XX____,
  _____X__,_____X__,__X_____,
  _____X__,_____X__,__X__X__,
  _____X__,_XXXXXXX,XXXXXXX_,
  _____X__,_____X__,__X_____,
  XXXXXXXX,X____X__,__X_____,
  _____X__,_____X__,__X_____,
  _____X__,________,________,
  _____X__,________,________,
  _____X__,_XXXXXXX,XXXXXXX_,
  _____XXX,X_X____X,X____X__,
  ____XX__,__X____X,X____X__,
  _XXX_X__,__X____X,X____X__,
  _XX__X__,__X____X,X____X__,
  _____X__,__XXXXXX,XXXXXX__,
  _____X__,__X____X,X____X__,
  _____X__,__X____X,X____X__,
  _____X__,__X____X,X____X__,
  _____X__,__X____X,X____X__,
  _X__XX__,__XXXXXX,XXXXXX__,
  __XXXX__,__X_____,_____X__,
  ____X___,__X_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_6570[ 72] = { /* code 6570 */
  _______X,_______X,________,
  __X____X,___X___X,X_______,
  ___X___X,___XX__X,X_______,
  ___XX__X,__X____X,________,
  ____X__X,__X___XX,________,
  ____X__X,_X_X__X_,________,
  _XXXXXXX,XXXXX_XX,XXXXXXX_,
  ______XX,_____XX_,___XX___,
  _____X_X,XX___XX_,___XX___,
  ____X__X,_XX__XX_,___XX___,
  ___X___X,__XXX__X,___XX___,
  __X____X,____X__X,___X____,
  XX____X_,___X___X,___X____,
  ______XX,__X____X,___X____,
  _XXXXXXX,XXXX___X,__XX____,
  _____X__,__X_____,X_X_____,
  ____XX__,_XX_____,X_X_____,
  ____X___,_X______,XXX_____,
  _____XXX,XX______,XXX_____,
  _______X,XXXX___X,X_XX____,
  ______X_,___X__XX,__XXX___,
  ____XX__,_____XX_,___XXXX_,
  _XXX____,___XX___,_____XX_,
  ________,__X_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_663E[ 63] = { /* code 663E */
  ________,________,_X______,
  ____XXXX,XXXXXXXX,XX______,
  ____XX__,________,XX______,
  ____XX__,________,XX______,
  ____XX__,________,XX______,
  ____XXXX,XXXXXXXX,XX______,
  ____XX__,________,XX______,
  ____XX__,________,XX______,
  ____XXXX,XXXXXXXX,XX______,
  ____XX__,________,XX______,
  ________,________,________,
  _______X,X____X__,________,
  _X______,X____X__,___X____,
  __X_____,X____X__,__XXX___,
  __XX____,X____X__,__X_____,
  ___XX___,X____X__,_XX_____,
  ____XX__,X____X__,XX______,
  ____X___,X____X_X,X_______,
  ____X___,X____XX_,________,
  ________,X____X__,____X___,
  XXXXXXXX,XXXXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_6682[ 72] = { /* code 6682 */
  _____X__,________,________,
  _____XX_,________,__XXX___,
  ____XX__,__X__XXX,XX______,
  XXXXXXXX,XXXX_X__,________,
  ____X___,_____X__,________,
  ___X___X,_____X__,________,
  __XX___X,__X__XXX,XXXXXX__,
  __XXXXXX,XXXX_X__,__X_____,
  _______X,_____X__,__X_____,
  _______X,_XXX_X__,__X_____,
  ___XXXXX,X___XX__,__X_____,
  XXXX___X,____X___,__X_____,
  ______XX,___X____,__X_____,
  ______X_,__X_____,_X______,
  ____XXXX,XXXXXXXX,XXX_____,
  ____XX__,________,_X______,
  ____XX__,________,_X______,
  ____XX__,________,_X______,
  ____XXXX,XXXXXXXX,XX______,
  ____XX__,________,_X______,
  ____XX__,________,_X______,
  ____XXXX,XXXXXXXX,XX______,
  ____XX__,________,_X______,
  ____X___,________,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_6807[ 72] = { /* code 6807 */
  ____X___,________,________,
  ____XX__,________,____X___,
  ____XX__,__XXXXXX,XXXXXX__,
  ____XX__,________,________,
  ____XX__,________,________,
  ____XX__,________,________,
  XXXXXXXX,X_______,________,
  ____XX__,________,________,
  ____XX__,_XXXXXXX,XXXXXXX_,
  ____XX__,_______X,X_______,
  ___XXXX_,_______X,X_______,
  ___XXX_X,X______X,X_______,
  ___XXX_X,X__XX__X,X_X_____,
  __XXXX__,X__XX__X,X__X____,
  __X_XX__,___X___X,X__XX___,
  __X_XX__,__XX___X,X___XX__,
  _X__XX__,__X____X,X___XX__,
  X___XX__,_XX____X,X____XX_,
  ____XX__,_X_____X,X____XX_,
  ____XX__,X______X,X____XX_,
  ____XX_X,_______X,X_______,
  ____XX__,____XXXX,X_______,
  ____XX__,______XX,X_______,
  ____XX__,_______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_6837[ 72] = { /* code 6837 */
  ____X___,________,___X____,
  ____XX__,___X____,__XXX___,
  ____XX__,____X___,__XX____,
  ____XX__,____XX__,__X_____,
  ____XX__,_____X__,_X______,
  ____XX__,_____X__,_X______,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  ____XX__,_______X,________,
  ____XX__,_______X,________,
  ____XX__,_______X,____X___,
  ___XXXX_,__XXXXXX,XXXXXX__,
  ___XXX_X,X______X,________,
  ___XXX_X,X______X,________,
  __XXXX__,X______X,________,
  __X_XX__,_______X,_____X__,
  _X__XX__,XXXXXXXX,XXXXXXX_,
  _X__XX__,_______X,________,
  X___XX__,_______X,________,
  ____XX__,_______X,________,
  ____XX__,_______X,________,
  ____XX__,_______X,________,
  ____XX__,_______X,________,
  ____XX__,_______X,________,
  ____XX__,_______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_6B65[ 72] = { /* code 6B65 */
  ________,____X___,________,
  ________,____XX__,________,
  ________,____X___,________,
  _____XX_,____X___,___X____,
  _____XX_,____XXXX,XXXXX___,
  _____XX_,____X___,________,
  _____XX_,____X___,________,
  _____XX_,____X___,________,
  _____XX_,____X___,_____X__,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,___X____,________,
  ________,____XX__,________,
  ______X_,____X___,____X___,
  ______XX,____X___,___XXX__,
  _____XX_,____X___,__XXX___,
  _____X__,____X___,__XX____,
  ____X___,____X___,XXX_____,
  ___XX___,____X__X,X_______,
  __XX____,___X__XX,________,
  _X______,____XXX_,________,
  ________,___XX___,________,
  ________,XXX_____,________,
  _____XXX,________,________,
  _XXXX___,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_6C34[ 72] = { /* code 6C34 */
  ________,___X____,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,___XX___,
  ________,___XX___,__XXX___,
  ________,X__XXX__,_XX_____,
  _XXXXXXX,XX_XXX__,XX______,
  _______X,X__XXX_X,________,
  _______X,X__XX_X_,________,
  _______X,___XX_X_,________,
  ______XX,___XX__X,________,
  ______X_,___XX__X,X_______,
  _____XX_,___XX___,X_______,
  _____XX_,___XX___,XX______,
  ____XX__,___XX___,_XX_____,
  ____X___,___XX___,__XX____,
  ___XX___,___XX___,__XXX___,
  ___X____,___XX___,___XXXX_,
  __X_____,___XX___,____XX__,
  _X_____X,X_XXX___,________,
  ________,_XXX____,________,
  ________,__X_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_6CE2[ 72] = { /* code 6CE2 */
  ________,_______X,________,
  ___X____,_______X,________,
  ___XX___,_______X,________,
  ____XX__,_______X,________,
  ____XX__,X______X,_____X__,
  _______X,_XXXXXXX,XXXXXXX_,
  _______X,_X_____X,____XX__,
  _X_____X,_X_____X,____X___,
  _XX___X_,_X_____X,___X____,
  __XX__X_,_X_____X,________,
  __XX__X_,_X_____X,________,
  _____X__,_XXXXXXX,XXXXX___,
  _____X__,_X__X___,___XX___,
  ____X___,_X__X___,___X____,
  ____X___,_X___X__,__XX____,
  ___XX___,_X___X__,__X_____,
  XXXX____,XX____X_,_X______,
  __XX____,X______X,XX______,
  ___X____,X______X,X_______,
  __XX___X,______XX,XX______,
  __XX___X,_____XX_,_XXX____,
  __XX__X_,____X___,__XXXX__,
  __XX_X__,_XXX____,____XXX_,
  ____X__X,X_______,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_6D4B[ 69] = { /* code 6D4B */
  __X_____,________,_____X__,
  ___XX__X,XXXXXXX_,_____X__,
  ____X__X,______X_,_____X__,
  ____X__X,______X_,_X___X__,
  _______X,______X_,_XX__X__,
  X______X,__XX__X_,_XX__X__,
  _X_____X,__XX__X_,_XX__X__,
  __X___XX,__XX__X_,_XX__X__,
  __XX_X_X,__XX__X_,_XX__X__,
  __X__X_X,__XX__X_,_XX__X__,
  _____X_X,__XX__X_,_XX__X__,
  ____X__X,__XX__X_,_XX__X__,
  ____X__X,__X___X_,_XX__X__,
  ____X__X,__X___X_,_XX__X__,
  ___XX__X,__X___X_,_XX__X__,
  XXXX___X,__X___X_,_XX__X__,
  __XX___X,_XX_____,_XX__X__,
  ___X____,_X_X____,_____X__,
  __XX____,_X__XX__,_____X__,
  __XX____,X____XX_,_____X__,
  __XX___X,______X_,_X___X__,
  ___X__X_,______X_,__XXXX__,
  _____X__,________,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_6D4F[ 69] = { /* code 6D4F */
  ________,_X______,_____X__,
  ___XX___,__X_____,_____XX_,
  ____XX__,__XX____,_____X__,
  _____X__,___X____,_____X__,
  _____X__,___X____,_XX__X__,
  _______X,XXXXXXXX,XX___X__,
  X_____X_,_____X__,_X___X__,
  _XX___X_,_____X__,_X___X__,
  __XX__XX,____XX__,_X___X__,
  __XX_X__,X___XX__,_X___X__,
  ___X_X__,_X__X___,_X___X__,
  _____X__,__X_X___,_X___X__,
  ____X___,__XXX___,_X___X__,
  ____X___,___XX___,_X___X__,
  ____X___,___XX___,_X___X__,
  ___XX___,__X_X___,_X___X__,
  _XXX____,_XX_XX__,_X___X__,
  ___X____,_X___X__,_____X__,
  ___X____,X____XX_,_____X__,
  ___X___X,_____XX_,_____X__,
  __XX__X_,________,_XX__X__,
  __XX____,________,___XXX__,
  ________,________,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_6E38[ 72] = { /* code 6E38 */
  ________,________,X_______,
  __XX____,X_______,XX______,
  ___XX___,_X______,X_______,
  ____X___,_XX_____,X_______,
  ____X___,__X____X,________,
  ______X_,_______X,XXXXXXX_,
  ______XX,XXXXXXX_,________,
  XX___X__,XX____X_,________,
  _XX__X__,XX___X_X,XXXXXXX_,
  __X__X__,XX__X___,____XX__,
  __X_X___,XXXXXX__,___X____,
  ____X___,XX__X___,__X_____,
  ____X___,X___X___,__X_____,
  ____X___,X___X___,__X_____,
  ___X____,X___X_XX,XXXXXXX_,
  ___X____,X___X___,__X_____,
  _XXX___X,X___X___,__X_____,
  __XX___X,____X___,__X_____,
  __XX___X,____X___,__X_____,
  __XX__X_,___XX___,__X_____,
  __XX__X_,___X____,__X_____,
  __XX_X__,XXXX____,__X_____,
  ____X___,__XX____,XXX_____,
  ___X____,________,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_6EE4[ 69] = { /* code 6EE4 */
  ________,______X_,________,
  ________,______XX,________,
  ___XX___,______X_,____X___,
  ____XX__,______XX,XXXXXX__,
  ____XX__,______X_,________,
  _____X_X,______X_,________,
  _______X,_XXXXXXX,XXXXXXX_,
  X_____X_,_X____XX,_____X__,
  _XX___X_,_X____X_,__XXX___,
  __XX__X_,_XXXXXXX,XX__X___,
  __XX_X__,_X____X_,____X___,
  _____X__,_X____X_,____XX__,
  _____X__,_X____XX,XXXXXX__,
  ____X___,XX______,________,
  ____X___,XX_____X,X_______,
  ___XX___,X____XX_,XX______,
  XXXX____,X__X_X__,_X__X___,
  __XX____,X__X_X__,___X_XX_,
  ___X___X,X_XX_X__,___X__X_,
  ___X___X,_XX__X__,___X__X_,
  __XX__X_,_____XX_,___XX___,
  __XX__X_,_____XXX,XXXXX___,
  ___X_X__,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_72B6[ 72] = { /* code 72B6 */
  ______X_,______X_,________,
  ______XX,______XX,________,
  ______XX,______X_,__XX____,
  ______XX,______X_,___XX___,
  ______XX,______X_,____XX__,
  _XX___XX,______X_,____X___,
  __XX__XX,______X_,________,
  __XX__XX,______X_,_____X__,
  ___XX_XX,XXXXXXXX,XXXXXXX_,
  ___X__XX,______X_,X_______,
  ______XX,______X_,X_______,
  ______XX,______X_,X_______,
  _____XXX,_____XX_,X_______,
  ____X_XX,_____XX_,_X______,
  ___X__XX,_____X__,_X______,
  _XX___XX,_____X__,_X______,
  XX____XX,____XX__,_XX_____,
  _X____XX,____X___,__X_____,
  ______XX,____X___,__XX____,
  ______XX,___X____,___XX___,
  ______XX,__XX____,___XXX__,
  ______XX,__X_____,____XXX_,
  ______XX,_X______,_____X__,
  ______X_,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_7387[ 72] = { /* code 7387 */
  ________,__X_____,________,
  ________,___XX___,________,
  ________,___XX___,____X___,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ________,___X____,________,
  ________,__XX____,___X____,
  ___XX___,_XX___XX,___XX___,
  ____XX__,X_____XX,__XX____,
  _____X_X,XXXXXX__,_X______,
  _____X__,X___X___,X_______,
  ________,___X____,________,
  ______X_,__X__X__,_XX_____,
  ____XX__,_X____XX,___XX___,
  __XX___X,XXXXXXXX,X___X___,
  __X_____,X__X___X,____X___,
  ________,___XX___,________,
  ________,___XX___,________,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_7535[ 69] = { /* code 7535 */
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  XXXXXXXX,XXXXXXXX,X_______,
  XX______,X______X,X_______,
  XX______,X______X,X_______,
  XX______,X______X,X_______,
  XX______,X______X,X_______,
  XXXXXXXX,XXXXXXXX,X_______,
  XX______,X______X,X_______,
  XX______,X______X,X_______,
  XX______,X______X,X_______,
  XX______,X______X,X_______,
  XXXXXXXX,XXXXXXXX,X_______,
  XX______,X______X,X_______,
  X_______,X_______,________,
  ________,X_______,__X_____,
  ________,X_______,__X_____,
  ________,X_______,__XX____,
  ________,X_______,__XX____,
  ________,XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_754C[ 69] = { /* code 754C */
  ________,________,________,
  ____XXXX,XXXXXXXX,XXX_____,
  ____X___,__XX____,_XX_____,
  ____X___,__XX____,_XX_____,
  ____XXXX,XXXXXXXX,XXX_____,
  ____X___,__XX____,_XX_____,
  ____X___,__XX____,_XX_____,
  ____X___,__XX____,_XX_____,
  ____XXXX,XXXXXXXX,XXX_____,
  ____X___,_X___X__,_X______,
  ________,XX____X_,________,
  _______X,X_____XX,________,
  ______XX,_______X,X_______,
  _____XX_,XX____XX,_XXXX___,
  ___XX___,X_____X_,__XXXX__,
  _XX____X,X_____X_,________,
  _______X,X_____X_,________,
  _______X,______X_,________,
  ______XX,______X_,________,
  ______X_,______XX,________,
  _____X__,______XX,________,
  ___XX___,______XX,________,
  _XX_____,______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_76F4[ 66] = { /* code 76F4 */
  ________,___X____,________,
  ________,___XX___,________,
  ________,___XX___,____X___,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ________,___X____,________,
  ________,___X____,________,
  _____XXX,XXXXXXXX,XXXX____,
  _____XX_,________,_XX_____,
  _____XX_,________,_XX_____,
  _____XX_,________,_XX_____,
  _____XXX,XXXXXXXX,XXX_____,
  _____XX_,________,_XX_____,
  _____XX_,________,_XX_____,
  _____XXX,XXXXXXXX,XXX_____,
  _____XX_,________,_XX_____,
  _____XX_,________,_XX_____,
  _____XX_,________,_XX_____,
  _____XXX,XXXXXXXX,XXX_____,
  _____XX_,________,_XX_____,
  _____XX_,________,_XX_____,
  _____XX_,________,_XX__X__,
  XXXXXXXX,XXXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_793A[ 69] = { /* code 793A */
  ________,________,___X____,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,_____X__,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,___XX___,________,
  ________,___XX___,________,
  ______X_,___XX___,________,
  ______XX,X__XX___,X_______,
  _____XX_,___XX___,_X______,
  _____XX_,___XX___,__X_____,
  ____XX__,___XX___,___XX___,
  ____X___,___XX___,___XXX__,
  ___X____,___XX___,____XX__,
  __X_____,___XX___,_____X__,
  _X______,___XX___,_____X__,
  X______X,XXXXX___,________,
  ________,_XXX____,________,
  ________,__X_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_79FB[ 69] = { /* code 79FB */
  ________,_______X,________,
  _______X,XX_____X,X_______,
  __XXXXX_,______XX,________,
  _____XX_,_____XXX,XXXXXX__,
  _____XX_,_____X__,____XX__,
  _____XX_,____X_X_,___XX___,
  _____XX_,_X_X___X,__XX____,
  XXXXXXXX,XXX____X,_XX_____,
  _____XX_,________,XX______,
  _____XX_,_______X,X_______,
  ____XXX_,______X_,_X______,
  ____XXXX,X___XX__,XXX_____,
  ___XXXX_,XXXX___X,X_______,
  ___X_XX_,_X_____X,XXXXXXX_,
  __XX_XX_,______X_,_____XX_,
  __X__XX_,_____X__,____XX__,
  _X___XX_,___XX_X_,___XX___,
  _X___XX_,__X____X,__XX____,
  X____XX_,_______X,_XX_____,
  _____XX_,________,XX______,
  _____XX_,______XX,________,
  _____XX_,___XXX__,________,
  _____X__,XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_7F6E[ 69] = { /* code 7F6E */
  ________,________,____X___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XX___,_X____X_,___XX___,
  ___XX___,_X____X_,___XX___,
  ___XX___,_X____X_,___XX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XX___,___X____,___X____,
  ________,___X____,____X___,
  __XXXXXX,XXXXXXXX,XXXXX___,
  ________,___X____,_X______,
  _____XXX,XXXXXXXX,XXX_____,
  _____XX_,________,_XX_____,
  _____XX_,________,_XX_____,
  _____XXX,XXXXXXXX,XXX_____,
  _____XX_,________,_XX_____,
  _____XX_,________,_XX_____,
  _____XXX,XXXXXXXX,XXX_____,
  _____XX_,________,_XX_____,
  _____XX_,________,_XX_____,
  _____XXX,XXXXXXXX,XXX_____,
  _____XX_,________,_XX_____,
  _____XX_,________,_XX__XX_,
  XXXXXXXX,XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_81EA[ 72] = { /* code 81EA */
  ______X_,________,________,
  ______XX,X_______,________,
  ______XX,________,________,
  ______X_,________,________,
  _____X__,______X_,________,
  XXXXXXXX,XXXXXXXX,X_______,
  XX______,______XX,________,
  XX______,______XX,________,
  XX______,______XX,________,
  XX______,______XX,________,
  XXXXXXXX,XXXXXXXX,________,
  XX______,______XX,________,
  XX______,______XX,________,
  XX______,______XX,________,
  XX______,______XX,________,
  XXXXXXXX,XXXXXXXX,________,
  XX______,______XX,________,
  XX______,______XX,________,
  XX______,______XX,________,
  XX______,______XX,________,
  XX______,______XX,________,
  XXXXXXXX,XXXXXXXX,________,
  XX______,______XX,________,
  XX______,______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_85CF[ 72] = { /* code 85CF */
  ________,XX____X_,________,
  ________,XX____X_,_____X__,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,XX____X_,__X_____,
  ________,XX____X_,___X____,
  ________,X_______,XX_XX___,
  __X_____,________,X__X_X__,
  __X__XXX,XXXXXXXX,XXXXXXX_,
  __X__XX_,______X_,X_______,
  __X__XX_,XXXXXXXX,X_______,
  _XXXXXX_,XX_X____,X___XX__,
  __X__XX_,XX_X____,X___X___,
  _____XX_,XX_X____,X__XX___,
  XXXXXXX_,XXXXXXX_,XX_X____,
  __XX_XX_,XX___XX_,_X_X____,
  __X__XX_,XX___XX_,_XXX____,
  __X__XX_,XXXXXXX_,_XX_____,
  __X__X__,XX_X_X__,_XX_____,
  __X__X__,XX_X____,XXX____X,
  _X___X__,XXXXXXXX,X_XX___X,
  _X__X___,X______X,___XX_X_,
  X___X___,_____XX_,____XXX_,
  ___X____,____X___,_____XX_,
  __X_____,___X____,_______X};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_884C[ 72] = { /* code 884C */
  ______X_,________,________,
  ______XX,________,____X___,
  _____XX_,___XXXXX,XXXXXX__,
  ____XX__,________,________,
  ____X___,________,________,
  ___X___X,________,________,
  __X____X,X_______,________,
  _X_____X,________,_____X__,
  ______XX,_XXXXXXX,XXXXXXX_,
  _____XX_,________,X_______,
  _____X__,________,X_______,
  ____XXX_,________,X_______,
  ___X_XX_,________,X_______,
  __X__XX_,________,X_______,
  _X___XX_,________,X_______,
  _____XX_,________,X_______,
  _____XX_,________,X_______,
  _____XX_,________,X_______,
  _____XX_,________,X_______,
  _____XX_,________,X_______,
  _____XX_,________,X_______,
  _____XX_,____XXXX,X_______,
  _____XX_,______XX,X_______,
  _____X__,_______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_8868[ 69] = { /* code 8868 */
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,____X___,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ________,___X____,________,
  ________,___X____,__X_____,
  ____XXXX,XXXXXXXX,XXXX____,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,_____X__,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,__XX____,___X____,
  ________,_XX_X___,__XX____,
  ________,XX__X___,_XX_____,
  _______X,X____X__,XX______,
  ______XX,______XX,________,
  ____XX_X,______X_,________,
  ___X___X,_______X,X_______,
  _XX____X,________,XX______,
  _______X,___XX___,_XXX____,
  _______X,_XX_____,__XXXXXX,
  ______XX,XX______,____XX__,
  _______X,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_89C8[ 72] = { /* code 89C8 */
  _______X,______X_,________,
  __X____X,X____XX_,________,
  __XX___X,_____X__,____X___,
  __X____X,_____XXX,XXXXXX__,
  __X____X,____X___,________,
  __X____X,____X__X,________,
  __XX___X,___X____,XX______,
  __XX___X,__X_____,_XX_____,
  __X____X,__X_____,__X_____,
  ________,________,________,
  ____XXXX,XXXXXXXX,XX______,
  ____XX__,________,_X______,
  ____XX__,________,_X______,
  ____XX__,__XX____,_X______,
  ____XX__,__XX____,_X______,
  ____XX__,__XX____,_X______,
  ____XX__,__X_XX__,_X______,
  ____XX__,_XX_X___,_X______,
  ____X___,_X__X___,________,
  ________,XX__X___,_____X__,
  _______X,X___X___,_____X__,
  ______XX,____X___,____XX__,
  ____XX__,____XXXX,XXXXXX__,
  XXXX____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_89E6[ 69] = { /* code 89E6 */
  _____X__,________,________,
  _____XX_,________,_XX_____,
  ____XX__,________,_X______,
  ____XXXX,XX______,_X______,
  ___XX___,XX______,_X______,
  ___X___X,X_______,_X______,
  __XX___X,_____XXX,XXXXXXX_,
  __XXXXXX,XXX__X__,_X___X__,
  _XXX__X_,__X__X__,_X___X__,
  X_XX__X_,__X__X__,_X___X__,
  __XXXXXX,XXX__X__,_X___X__,
  __XX__X_,__X__X__,_X___X__,
  __XX__X_,__X__X__,_X___X__,
  __XX__X_,__X__X__,_X___X__,
  __XXXXXX,XXX__XXX,XXXXXX__,
  __XX__X_,__X__X__,_X___X__,
  __XX__X_,__X_____,_X______,
  __X___X_,__X_____,_X__X___,
  __X___X_,__X_____,_X___X__,
  __X___X_,__X_____,_X___XX_,
  _X____X_,__X_____,_XXXXXX_,
  _X______,XXXXXXXX,X_____XX,
  X_______,_X__X___,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_8BBE[ 69] = { /* code 8BBE */
  ___X____,________,________,
  ____XX__,___XXXXX,XXX_____,
  ____XX__,___XX___,_XX_____,
  _____X__,___XX___,_XX_____,
  ________,___XX___,_XX_____,
  ________,___X____,_XX_____,
  ________,___X____,_XX___X_,
  ________,__XX____,_XXXXXX_,
  _XXXXXX_,__X_____,________,
  _____X__,_X______,________,
  _____X__,XXXXXXXX,XXXX____,
  _____X__,___X____,__XX____,
  _____X__,____X___,__XX____,
  _____X__,____X___,__X_____,
  _____X__,_____X__,_XX_____,
  _____X__,_X___X__,_X______,
  _____X__,X_____X_,XX______,
  _____X_X,______XX,X_______,
  _____XX_,______XX,X_______,
  ____XXX_,_____X__,XXX_____,
  _____X__,___XX___,__XXXX__,
  ________,_XX_____,___XXXX_,
  ______XX,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_8FD0[ 63] = { /* code 8FD0 */
  ___X____,________,________,
  ___XX___,________,___X____,
  ____XX__,_XXXXXXX,XXXXX___,
  ____XX__,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,_____X__,
  XXXXXX_X,XXXXXXXX,XXXXXXX_,
  ____XX__,_____XX_,________,
  ____XX__,_____XX_,________,
  ____XX__,_____X__,________,
  ____XX__,____X___,________,
  ____XX__,___XX___,_X______,
  ____XX__,___X____,__XX____,
  ____XX__,__X_____,___XX___,
  ____XX__,XXXXXXXX,XXXXX___,
  ____XX__,_XXX____,____X___,
  __XX__X_,________,____X___,
  XXX____X,X_______,________,
  _X______,XXXXXXXX,XXXXXXX_,
  ________,___XXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_8FDB[ 69] = { /* code 8FDB */
  ________,___X____,_X______,
  ___X____,____X___,_XX_____,
  ____X___,____X___,_X______,
  ____XX__,____X___,_X______,
  _____X__,____X___,_X______,
  _______X,XXXXXXXX,XXXXXX__,
  ________,____X___,_X______,
  ________,____X___,_X______,
  ________,____X___,_X______,
  XXXXXX__,____X___,_X______,
  ____X___,____X___,_X______,
  ____X___,____X___,_X______,
  ____X__X,XXXXXXXX,XXXXXXX_,
  ____X___,____X___,_X______,
  ____X___,___XX___,_X______,
  ____X___,___X____,_X______,
  ____X___,___X____,_X______,
  ____X___,__X_____,_X______,
  ____X___,_X______,_X______,
  ___X_XX_,X_______,_X______,
  _XX____X,________,_X______,
  XX______,XXXXXXXX,XXXXXXXX,
  _X______,___XXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_91C7[ 72] = { /* code 91C7 */
  ________,________,___XX___,
  ________,_______X,XXXXXX__,
  ___XXXXX,XXXXXXX_,________,
  ________,________,__X_____,
  ________,__X_____,__XXX___,
  ____X___,___XX___,__X_____,
  ____XX__,___XX___,_XX_____,
  _____XX_,____X___,_X______,
  _____XX_,________,X_______,
  ________,___XX__X,________,
  ________,___XX___,_____X__,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,__XXXX__,________,
  ________,_XXXX_X_,________,
  ________,XX_XX_X_,________,
  ________,X__XX__X,________,
  _______X,X__XX__X,________,
  ______XX,___XX___,X_______,
  _____XX_,___XX___,_X______,
  ____XX__,___XX___,_XX_____,
  ___X____,___XX___,__XXX___,
  _XX_____,___XX___,___XXXXX,
  X_______,___XX___,_____X__,
  ________,___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_91CF[ 69] = { /* code 91CF */
  ________,________,__X_____,
  _____XXX,XXXXXXXX,XXX_____,
  _____X__,________,_XX_____,
  _____XXX,XXXXXXXX,XXX_____,
  _____X__,________,_XX_____,
  _____XXX,XXXXXXXX,XXX_____,
  _____X__,________,_XX_____,
  ____X___,________,______X_,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  ________,________,________,
  _____XXX,XXXXXXXX,XXXX____,
  _____X__,___XX___,__X_____,
  _____X__,___XX___,__X_____,
  _____XXX,XXXXXXXX,XXX_____,
  _____X__,___XX___,__X_____,
  _____X__,___XX___,__X_____,
  _____XXX,XXXXXXXX,XXX_____,
  _____X__,___XX___,__X_____,
  ________,___XX___,___X____,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ________,___XX___,________,
  ________,___XX___,_____X__,
  _XXXXXXX,XXXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_9636[ 69] = { /* code 9636 */
  ________,_____X__,________,
  ________,_____XX_,________,
  XXXXXXX_,____XXX_,________,
  XX___XX_,____X_X_,________,
  XX___X__,___XX__X,________,
  XX___X__,___X____,X_______,
  XX__X___,__X_____,XX______,
  XX__X___,_X______,_XX_____,
  XX_X____,X_X_____,__XXXX__,
  XX__X__X,__XX____,X___XX__,
  XX__XXX_,__XX____,XX______,
  XX___X__,__XX____,X_______,
  XX___XX_,__XX____,X_______,
  XX____X_,__XX____,X_______,
  XX____X_,__XX____,X_______,
  XX____X_,__XX____,X_______,
  XXXXXX__,__X_____,X_______,
  XX__X___,__X_____,X_______,
  XX______,__X_____,X_______,
  XX______,_X______,X_______,
  XX______,X_______,X_______,
  XX_____X,________,X_______,
  X_____X_,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_9690[ 69] = { /* code 9690 */
  _____X__,___X____,________,
  XXXXXXX_,__XXX___,________,
  X____X__,__XX____,X_______,
  X___XX__,__XXXXXX,XX______,
  X___X___,_XX____X,X_______,
  X___X___,_X_____X,________,
  X__X____,X_____X_,__XX____,
  X__X___X,_XXXXXXX,XXXX____,
  X__X__X_,________,__XX____,
  X___X___,________,__XX____,
  X____X__,XXXXXXXX,XXXX____,
  X____X__,________,__XX____,
  X____XX_,________,__XX____,
  X____XXX,XXXXXXXX,XXXX____,
  X____X__,____X___,__XX____,
  X__XXX__,_X___X__,________,
  X___X__X,_XX__XX_,__X_____,
  X______X,_XX___X_,___X____,
  X_____X_,_XX_____,_X__X___,
  X____XX_,_XX_____,_X__X___,
  X____XX_,__X_____,XX__X___,
  X_______,__XXXXXX,XX______,
  X_______,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_9762[ 69] = { /* code 9762 */
  ________,________,_____XX_,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,__XX____,________,
  ________,__X_____,________,
  ________,__X_____,________,
  ________,_X______,________,
  ___XXXXX,XXXXXXXX,XXXXXX__,
  ___X____,XX____X_,____X___,
  ___X____,XX____X_,____X___,
  ___X____,XX____X_,____X___,
  ___X____,XXXXXXX_,____X___,
  ___X____,XX____X_,____X___,
  ___X____,XX____X_,____X___,
  ___X____,XX____X_,____X___,
  ___X____,XX____X_,____X___,
  ___X____,XXXXXXX_,____X___,
  ___X____,XX____X_,____X___,
  ___X____,XX____X_,____X___,
  ___X____,XX____X_,____X___,
  ___X____,XX____X_,____X___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___X____,________,____X___,
  ___X____,________,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong26_9891[ 69] = { /* code 9891 */
  ______X_,________,________,
  ______XX,___XXXXX,XXXXXXX_,
  ______XX,________,_X______,
  ___X__XX,________,XX______,
  ___XX_XX,XXX_____,X_______,
  ___X__XX,________,X_______,
  ___X__XX,_____XXX,XXXXXXX_,
  ___X__XX,_____X__,_____XX_,
  ___X__XX,__X__X__,_____XX_,
  XXXXXXXX,XXXX_X__,_XX__XX_,
  ______X_,_____X__,_X___XX_,
  ______X_,_____X__,_X___XX_,
  ___X__X_,__X__X__,_X___XX_,
  ___XX_X_,__XX_X__,_X___XX_,
  __XX__X_,_XX__X__,_X___XX_,
  __X___X_,_X___X__,_X___XX_,
  _X____X_,XX___X__,_X___XX_,
  X_____XX,X____X__,XX___X__,
  ______XX,________,X_XX____,
  _____XX_,_______X,____XX__,
  ____XX__,______X_,_____XX_,
  __XX____,____XX__,______X_,
  _X______,__XX____,________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontFontSong26_CharInfo[114] = {
   {   1,   1,   0,  22,  13, acGUI_FontFontSong26_0020 } /* code 0020, SPACE */
  ,{  11,  22,   1,   2,  13, acGUI_FontFontSong26_002F } /* code 002F, SOLIDUS */
  ,{  11,  18,   1,   4,  13, acGUI_FontFontSong26_0030 } /* code 0030, DIGIT ZERO */
  ,{   8,  18,   3,   4,  13, acGUI_FontFontSong26_0031 } /* code 0031, DIGIT ONE */
  ,{  10,  18,   1,   4,  13, acGUI_FontFontSong26_0032 } /* code 0032, DIGIT TWO */
  ,{   9,  18,   2,   4,  13, acGUI_FontFontSong26_0033 } /* code 0033, DIGIT THREE */
  ,{  11,  18,   1,   4,  13, acGUI_FontFontSong26_0034 } /* code 0034, DIGIT FOUR */
  ,{   9,  18,   2,   4,  13, acGUI_FontFontSong26_0035 } /* code 0035, DIGIT FIVE */
  ,{  11,  18,   1,   4,  13, acGUI_FontFontSong26_0036 } /* code 0036, DIGIT SIX */
  ,{   9,  18,   2,   4,  13, acGUI_FontFontSong26_0037 } /* code 0037, DIGIT SEVEN */
  ,{  10,  18,   1,   4,  13, acGUI_FontFontSong26_0038 } /* code 0038, DIGIT EIGHT */
  ,{  11,  18,   1,   4,  13, acGUI_FontFontSong26_0039 } /* code 0039, DIGIT NINE */
  ,{  12,  18,   0,   4,  13, acGUI_FontFontSong26_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{  11,  18,   1,   4,  13, acGUI_FontFontSong26_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{  11,  18,   1,   4,  13, acGUI_FontFontSong26_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{  12,  18,   0,   4,  13, acGUI_FontFontSong26_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{  12,  18,   0,   4,  13, acGUI_FontFontSong26_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{  12,  18,   0,   4,  13, acGUI_FontFontSong26_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{  12,  18,   1,   4,  13, acGUI_FontFontSong26_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{  11,  18,   1,   4,  13, acGUI_FontFontSong26_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   8,  18,   3,   4,  13, acGUI_FontFontSong26_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{  11,  21,   1,   4,  13, acGUI_FontFontSong26_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{  12,  18,   0,   4,  13, acGUI_FontFontSong26_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{  12,  18,   0,   4,  13, acGUI_FontFontSong26_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  11,  18,   1,   4,  13, acGUI_FontFontSong26_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{  13,  18,   0,   4,  13, acGUI_FontFontSong26_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{  11,  18,   1,   4,  13, acGUI_FontFontSong26_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{  12,  18,   0,   4,  13, acGUI_FontFontSong26_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  11,  20,   1,   4,  13, acGUI_FontFontSong26_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{  12,  18,   0,   4,  13, acGUI_FontFontSong26_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{  10,  18,   1,   4,  13, acGUI_FontFontSong26_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{  12,  18,   1,   4,  13, acGUI_FontFontSong26_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{  12,  18,   1,   4,  13, acGUI_FontFontSong26_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{  12,  18,   0,   4,  13, acGUI_FontFontSong26_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  13,  18,   0,   4,  13, acGUI_FontFontSong26_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{  11,  18,   1,   4,  13, acGUI_FontFontSong26_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{  12,  18,   1,   4,  13, acGUI_FontFontSong26_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{  11,  18,   1,   4,  13, acGUI_FontFontSong26_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{  11,  12,   1,  10,  13, acGUI_FontFontSong26_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{  12,  19,   0,   3,  13, acGUI_FontFontSong26_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   9,  12,   2,  10,  13, acGUI_FontFontSong26_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{  11,  19,   2,   3,  13, acGUI_FontFontSong26_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   9,  12,   2,  10,  13, acGUI_FontFontSong26_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{  10,  18,   2,   4,  13, acGUI_FontFontSong26_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{  11,  15,   1,  10,  13, acGUI_FontFontSong26_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{  11,  19,   1,   3,  13, acGUI_FontFontSong26_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   8,  18,   3,   4,  13, acGUI_FontFontSong26_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   9,  21,   2,   4,  13, acGUI_FontFontSong26_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{  12,  19,   0,   3,  13, acGUI_FontFontSong26_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   8,  19,   3,   3,  13, acGUI_FontFontSong26_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{  14,  12,   0,  10,  13, acGUI_FontFontSong26_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{  11,  12,   1,  10,  13, acGUI_FontFontSong26_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{  11,  12,   1,  10,  13, acGUI_FontFontSong26_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{  12,  15,   0,  10,  13, acGUI_FontFontSong26_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{  12,  15,   1,  10,  13, acGUI_FontFontSong26_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{  11,  12,   1,  10,  13, acGUI_FontFontSong26_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   9,  12,   2,  10,  13, acGUI_FontFontSong26_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   9,  16,   2,   6,  13, acGUI_FontFontSong26_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{  13,  13,   0,   9,  13, acGUI_FontFontSong26_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{  11,  12,   1,  10,  13, acGUI_FontFontSong26_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{  13,  12,   0,  10,  13, acGUI_FontFontSong26_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{  11,  15,   1,  10,  13, acGUI_FontFontSong26_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   9,  12,   2,  10,  13, acGUI_FontFontSong26_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{  24,  23,   1,   1,  26, acGUI_FontFontSong26_4F4D } /* code 4F4D */
  ,{  24,  24,   1,   1,  26, acGUI_FontFontSong26_505C } /* code 505C */
  ,{  23,  24,   1,   1,  26, acGUI_FontFontSong26_52A8 } /* code 52A8 */
  ,{  24,  23,   1,   1,  26, acGUI_FontFontSong26_538B } /* code 538B */
  ,{  24,  23,   1,   1,  26, acGUI_FontFontSong26_53C2 } /* code 53C2 */
  ,{  24,  24,   1,   1,  26, acGUI_FontFontSong26_53D1 } /* code 53D1 */
  ,{  24,  23,   1,   1,  26, acGUI_FontFontSong26_5668 } /* code 5668 */
  ,{  24,  23,   1,   1,  26, acGUI_FontFontSong26_5782 } /* code 5782 */
  ,{  23,  23,   2,   1,  26, acGUI_FontFontSong26_5B66 } /* code 5B66 */
  ,{  23,  24,   2,   1,  26, acGUI_FontFontSong26_5E45 } /* code 5E45 */
  ,{  24,  23,   1,   1,  26, acGUI_FontFontSong26_5E73 } /* code 5E73 */
  ,{  23,  24,   1,   1,  26, acGUI_FontFontSong26_5EA6 } /* code 5EA6 */
  ,{  24,  22,   1,   2,  26, acGUI_FontFontSong26_5F62 } /* code 5F62 */
  ,{  24,  23,   1,   1,  26, acGUI_FontFontSong26_6001 } /* code 6001 */
  ,{  23,  23,   1,   1,  26, acGUI_FontFontSong26_626B } /* code 626B */
  ,{  24,  23,   1,   1,  26, acGUI_FontFontSong26_63CF } /* code 63CF */
  ,{  24,  24,   1,   1,  26, acGUI_FontFontSong26_6570 } /* code 6570 */
  ,{  22,  21,   2,   1,  26, acGUI_FontFontSong26_663E } /* code 663E */
  ,{  23,  24,   2,   1,  26, acGUI_FontFontSong26_6682 } /* code 6682 */
  ,{  24,  24,   1,   1,  26, acGUI_FontFontSong26_6807 } /* code 6807 */
  ,{  24,  24,   1,   1,  26, acGUI_FontFontSong26_6837 } /* code 6837 */
  ,{  24,  24,   1,   1,  26, acGUI_FontFontSong26_6B65 } /* code 6B65 */
  ,{  24,  24,   1,   1,  26, acGUI_FontFontSong26_6C34 } /* code 6C34 */
  ,{  24,  24,   1,   1,  26, acGUI_FontFontSong26_6CE2 } /* code 6CE2 */
  ,{  23,  23,   1,   1,  26, acGUI_FontFontSong26_6D4B } /* code 6D4B */
  ,{  23,  23,   1,   1,  26, acGUI_FontFontSong26_6D4F } /* code 6D4F */
  ,{  24,  24,   1,   1,  26, acGUI_FontFontSong26_6E38 } /* code 6E38 */
  ,{  24,  23,   1,   1,  26, acGUI_FontFontSong26_6EE4 } /* code 6EE4 */
  ,{  24,  24,   1,   1,  26, acGUI_FontFontSong26_72B6 } /* code 72B6 */
  ,{  24,  24,   1,   1,  26, acGUI_FontFontSong26_7387 } /* code 7387 */
  ,{  20,  23,   4,   1,  26, acGUI_FontFontSong26_7535 } /* code 7535 */
  ,{  23,  23,   2,   1,  26, acGUI_FontFontSong26_754C } /* code 754C */
  ,{  24,  22,   1,   1,  26, acGUI_FontFontSong26_76F4 } /* code 76F4 */
  ,{  24,  23,   1,   1,  26, acGUI_FontFontSong26_793A } /* code 793A */
  ,{  24,  23,   1,   1,  26, acGUI_FontFontSong26_79FB } /* code 79FB */
  ,{  24,  23,   1,   1,  26, acGUI_FontFontSong26_7F6E } /* code 7F6E */
  ,{  17,  24,   5,   1,  26, acGUI_FontFontSong26_81EA } /* code 81EA */
  ,{  24,  24,   1,   1,  26, acGUI_FontFontSong26_85CF } /* code 85CF */
  ,{  24,  24,   1,   1,  26, acGUI_FontFontSong26_884C } /* code 884C */
  ,{  24,  23,   1,   1,  26, acGUI_FontFontSong26_8868 } /* code 8868 */
  ,{  23,  24,   2,   1,  26, acGUI_FontFontSong26_89C8 } /* code 89C8 */
  ,{  24,  23,   1,   1,  26, acGUI_FontFontSong26_89E6 } /* code 89E6 */
  ,{  24,  23,   1,   1,  26, acGUI_FontFontSong26_8BBE } /* code 8BBE */
  ,{  24,  21,   1,   2,  26, acGUI_FontFontSong26_8FD0 } /* code 8FD0 */
  ,{  24,  23,   1,   1,  26, acGUI_FontFontSong26_8FDB } /* code 8FDB */
  ,{  24,  24,   1,   1,  26, acGUI_FontFontSong26_91C7 } /* code 91C7 */
  ,{  24,  23,   1,   1,  26, acGUI_FontFontSong26_91CF } /* code 91CF */
  ,{  23,  23,   2,   1,  26, acGUI_FontFontSong26_9636 } /* code 9636 */
  ,{  21,  23,   3,   1,  26, acGUI_FontFontSong26_9690 } /* code 9690 */
  ,{  24,  23,   1,   1,  26, acGUI_FontFontSong26_9762 } /* code 9762 */
  ,{  24,  23,   1,   1,  26, acGUI_FontFontSong26_9891 } /* code 9891 */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop56 = {
   0x9891 /* first character */
  ,0x9891 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[113] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop55 = {
   0x9762 /* first character */
  ,0x9762 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[112] /* address of first character */
  ,&GUI_FontFontSong26_Prop56 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop54 = {
   0x9690 /* first character */
  ,0x9690 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[111] /* address of first character */
  ,&GUI_FontFontSong26_Prop55 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop53 = {
   0x9636 /* first character */
  ,0x9636 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[110] /* address of first character */
  ,&GUI_FontFontSong26_Prop54 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop52 = {
   0x91CF /* first character */
  ,0x91CF /* last character  */
  ,&GUI_FontFontSong26_CharInfo[109] /* address of first character */
  ,&GUI_FontFontSong26_Prop53 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop51 = {
   0x91C7 /* first character */
  ,0x91C7 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[108] /* address of first character */
  ,&GUI_FontFontSong26_Prop52 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop50 = {
   0x8FDB /* first character */
  ,0x8FDB /* last character  */
  ,&GUI_FontFontSong26_CharInfo[107] /* address of first character */
  ,&GUI_FontFontSong26_Prop51 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop49 = {
   0x8FD0 /* first character */
  ,0x8FD0 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[106] /* address of first character */
  ,&GUI_FontFontSong26_Prop50 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop48 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_FontFontSong26_CharInfo[105] /* address of first character */
  ,&GUI_FontFontSong26_Prop49 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop47 = {
   0x89E6 /* first character */
  ,0x89E6 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[104] /* address of first character */
  ,&GUI_FontFontSong26_Prop48 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop46 = {
   0x89C8 /* first character */
  ,0x89C8 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[103] /* address of first character */
  ,&GUI_FontFontSong26_Prop47 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop45 = {
   0x8868 /* first character */
  ,0x8868 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[102] /* address of first character */
  ,&GUI_FontFontSong26_Prop46 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop44 = {
   0x884C /* first character */
  ,0x884C /* last character  */
  ,&GUI_FontFontSong26_CharInfo[101] /* address of first character */
  ,&GUI_FontFontSong26_Prop45 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop43 = {
   0x85CF /* first character */
  ,0x85CF /* last character  */
  ,&GUI_FontFontSong26_CharInfo[100] /* address of first character */
  ,&GUI_FontFontSong26_Prop44 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop42 = {
   0x81EA /* first character */
  ,0x81EA /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 99] /* address of first character */
  ,&GUI_FontFontSong26_Prop43 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop41 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 98] /* address of first character */
  ,&GUI_FontFontSong26_Prop42 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop40 = {
   0x79FB /* first character */
  ,0x79FB /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 97] /* address of first character */
  ,&GUI_FontFontSong26_Prop41 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop39 = {
   0x793A /* first character */
  ,0x793A /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 96] /* address of first character */
  ,&GUI_FontFontSong26_Prop40 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop38 = {
   0x76F4 /* first character */
  ,0x76F4 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 95] /* address of first character */
  ,&GUI_FontFontSong26_Prop39 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop37 = {
   0x754C /* first character */
  ,0x754C /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 94] /* address of first character */
  ,&GUI_FontFontSong26_Prop38 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop36 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 93] /* address of first character */
  ,&GUI_FontFontSong26_Prop37 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop35 = {
   0x7387 /* first character */
  ,0x7387 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 92] /* address of first character */
  ,&GUI_FontFontSong26_Prop36 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop34 = {
   0x72B6 /* first character */
  ,0x72B6 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 91] /* address of first character */
  ,&GUI_FontFontSong26_Prop35 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop33 = {
   0x6EE4 /* first character */
  ,0x6EE4 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 90] /* address of first character */
  ,&GUI_FontFontSong26_Prop34 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop32 = {
   0x6E38 /* first character */
  ,0x6E38 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 89] /* address of first character */
  ,&GUI_FontFontSong26_Prop33 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop31 = {
   0x6D4F /* first character */
  ,0x6D4F /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 88] /* address of first character */
  ,&GUI_FontFontSong26_Prop32 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop30 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 87] /* address of first character */
  ,&GUI_FontFontSong26_Prop31 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop29 = {
   0x6CE2 /* first character */
  ,0x6CE2 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 86] /* address of first character */
  ,&GUI_FontFontSong26_Prop30 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop28 = {
   0x6C34 /* first character */
  ,0x6C34 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 85] /* address of first character */
  ,&GUI_FontFontSong26_Prop29 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop27 = {
   0x6B65 /* first character */
  ,0x6B65 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 84] /* address of first character */
  ,&GUI_FontFontSong26_Prop28 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop26 = {
   0x6837 /* first character */
  ,0x6837 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 83] /* address of first character */
  ,&GUI_FontFontSong26_Prop27 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop25 = {
   0x6807 /* first character */
  ,0x6807 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 82] /* address of first character */
  ,&GUI_FontFontSong26_Prop26 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop24 = {
   0x6682 /* first character */
  ,0x6682 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 81] /* address of first character */
  ,&GUI_FontFontSong26_Prop25 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop23 = {
   0x663E /* first character */
  ,0x663E /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 80] /* address of first character */
  ,&GUI_FontFontSong26_Prop24 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop22 = {
   0x6570 /* first character */
  ,0x6570 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 79] /* address of first character */
  ,&GUI_FontFontSong26_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop21 = {
   0x63CF /* first character */
  ,0x63CF /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 78] /* address of first character */
  ,&GUI_FontFontSong26_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop20 = {
   0x626B /* first character */
  ,0x626B /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 77] /* address of first character */
  ,&GUI_FontFontSong26_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop19 = {
   0x6001 /* first character */
  ,0x6001 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 76] /* address of first character */
  ,&GUI_FontFontSong26_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop18 = {
   0x5F62 /* first character */
  ,0x5F62 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 75] /* address of first character */
  ,&GUI_FontFontSong26_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop17 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 74] /* address of first character */
  ,&GUI_FontFontSong26_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop16 = {
   0x5E73 /* first character */
  ,0x5E73 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 73] /* address of first character */
  ,&GUI_FontFontSong26_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop15 = {
   0x5E45 /* first character */
  ,0x5E45 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 72] /* address of first character */
  ,&GUI_FontFontSong26_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop14 = {
   0x5B66 /* first character */
  ,0x5B66 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 71] /* address of first character */
  ,&GUI_FontFontSong26_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop13 = {
   0x5782 /* first character */
  ,0x5782 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 70] /* address of first character */
  ,&GUI_FontFontSong26_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop12 = {
   0x5668 /* first character */
  ,0x5668 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 69] /* address of first character */
  ,&GUI_FontFontSong26_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop11 = {
   0x53D1 /* first character */
  ,0x53D1 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 68] /* address of first character */
  ,&GUI_FontFontSong26_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop10 = {
   0x53C2 /* first character */
  ,0x53C2 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 67] /* address of first character */
  ,&GUI_FontFontSong26_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop9 = {
   0x538B /* first character */
  ,0x538B /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 66] /* address of first character */
  ,&GUI_FontFontSong26_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop8 = {
   0x52A8 /* first character */
  ,0x52A8 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 65] /* address of first character */
  ,&GUI_FontFontSong26_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop7 = {
   0x505C /* first character */
  ,0x505C /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 64] /* address of first character */
  ,&GUI_FontFontSong26_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop6 = {
   0x4F4D /* first character */
  ,0x4F4D /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 63] /* address of first character */
  ,&GUI_FontFontSong26_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop5 = {
   0x0079 /* first character */
  ,0x007A /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 61] /* address of first character */
  ,&GUI_FontFontSong26_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop4 = {
   0x0061 /* first character */
  ,0x0077 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 38] /* address of first character */
  ,&GUI_FontFontSong26_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop3 = {
   0x0041 /* first character */
  ,0x005A /* last character  */
  ,&GUI_FontFontSong26_CharInfo[ 12] /* address of first character */
  ,&GUI_FontFontSong26_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop2 = {
   0x002F /* first character */
  ,0x0039 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[  1] /* address of first character */
  ,&GUI_FontFontSong26_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong26_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontFontSong26_CharInfo[  0] /* address of first character */
  ,&GUI_FontFontSong26_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFontSong26 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,26 /* height of font  */
  ,26 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFontSong26_Prop1}
  ,22 /* Baseline */
  ,12 /* Height of lowercase characters */
  ,18 /* Height of capital characters */
};

