/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.40                      *
*        Compiled Mar 17 2017, 15:34:36                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: FontSong20.c                                          *
* Font:        ËÎÌå                                                  *
* Height:      20                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  20                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: D:\¿ÎÉè\emwin×ÖÌå\1.txt                         *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFontSong20;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_002F[ 17] = { /* code 002F, SOLIDUS */
  _______X,
  _______X,
  ______X_,
  ______X_,
  _____X__,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  _X______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0030[ 14] = { /* code 0030, DIGIT ZERO */
  __XXXX__,
  _X____X_,
  _X____X_,
  X______X,
  X______X,
  X______X,
  X______X,
  X______X,
  X______X,
  X______X,
  X______X,
  _X____X_,
  _X____X_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0031[ 14] = { /* code 0031, DIGIT ONE */
  __X_____,
  XXX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0032[ 14] = { /* code 0032, DIGIT TWO */
  __XXXX__,
  _X____X_,
  X______X,
  X______X,
  X______X,
  _______X,
  ______X_,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X_____X,
  X______X,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0033[ 14] = { /* code 0033, DIGIT THREE */
  _XXXX___,
  X____X__,
  X_____X_,
  X_____X_,
  ______X_,
  _____X__,
  ___XXX__,
  ______X_,
  _______X,
  _______X,
  X______X,
  X______X,
  X_____X_,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0034[ 14] = { /* code 0034, DIGIT FOUR */
  _____X__,
  ____XX__,
  ____XX__,
  ___X_X__,
  ___X_X__,
  __X__X__,
  _X___X__,
  _X___X__,
  X____X__,
  XXXXXXXX,
  _____X__,
  _____X__,
  _____X__,
  ___XXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0035[ 14] = { /* code 0035, DIGIT FIVE */
  _XXXXXXX,
  _X______,
  _X______,
  _X______,
  _X______,
  _X_XXX__,
  _XX___X_,
  _______X,
  _______X,
  _______X,
  X______X,
  X______X,
  X_____X_,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0036[ 14] = { /* code 0036, DIGIT SIX */
  ___XXX__,
  __X___X_,
  _X____X_,
  X_______,
  X_______,
  X_XXXX__,
  XX____X_,
  X______X,
  X______X,
  X______X,
  X______X,
  _X_____X,
  _X____X_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0037[ 14] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,
  X______X,
  X_____X_,
  _____X__,
  _____X__,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0038[ 14] = { /* code 0038, DIGIT EIGHT */
  __XXXX__,
  _X____X_,
  X______X,
  X______X,
  X______X,
  _X____X_,
  __XXXX__,
  _X____X_,
  X______X,
  X______X,
  X______X,
  X______X,
  _X____X_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0039[ 14] = { /* code 0039, DIGIT NINE */
  __XXXX__,
  _X____X_,
  X_____X_,
  X______X,
  X______X,
  X______X,
  X_____XX,
  _X___X_X,
  __XXX__X,
  _______X,
  ______X_,
  _X____X_,
  _X___X__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0041[ 26] = { /* code 0041, LATIN CAPITAL LETTER A */
  ____X___,________,
  ____X___,________,
  ___X_X__,________,
  ___X_X__,________,
  ___X_X__,________,
  ___X_X__,________,
  __X___X_,________,
  __X___X_,________,
  __XXXXX_,________,
  __X___X_,________,
  _X_____X,________,
  _X_____X,________,
  XXX___XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0042[ 13] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  _XXXXX__,
  _X____X_,
  _X_____X,
  _X_____X,
  _X_____X,
  _X_____X,
  _X____X_,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0043[ 26] = { /* code 0043, LATIN CAPITAL LETTER C */
  ___XXXX_,X_______,
  __X____X,X_______,
  _X______,X_______,
  _X______,X_______,
  X_______,________,
  X_______,________,
  X_______,________,
  X_______,________,
  X_______,________,
  X_______,X_______,
  _X______,X_______,
  _XX____X,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0044[ 26] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXXX__,________,
  _X____X_,________,
  _X_____X,________,
  _X______,X_______,
  _X______,X_______,
  _X______,X_______,
  _X______,X_______,
  _X______,X_______,
  _X______,X_______,
  _X______,X_______,
  _X_____X,________,
  _X____X_,________,
  XXXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0045[ 26] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXXXXX,________,
  _X_____X,________,
  _X______,X_______,
  _X____X_,________,
  _X____X_,________,
  _XXXXXX_,________,
  _X____X_,________,
  _X____X_,________,
  _X______,________,
  _X______,________,
  _X______,X_______,
  _X_____X,________,
  XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0046[ 26] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXXXXX,________,
  _X_____X,________,
  _X______,X_______,
  _X____X_,________,
  _X____X_,________,
  _XXXXXX_,________,
  _X____X_,________,
  _X____X_,________,
  _X______,________,
  _X______,________,
  _X______,________,
  _X______,________,
  XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0047[ 26] = { /* code 0047, LATIN CAPITAL LETTER G */
  ___XXX_X,________,
  __X___XX,________,
  _X_____X,________,
  X______X,________,
  X_______,________,
  X_______,________,
  X_______,________,
  X_____XX,X_______,
  X______X,________,
  X______X,________,
  _X_____X,________,
  _XX____X,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0048[ 26] = { /* code 0048, LATIN CAPITAL LETTER H */
  XXX___XX,X_______,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________,
  _XXXXXXX,________,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________,
  XXX___XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0049[ 13] = { /* code 0049, LATIN CAPITAL LETTER I */
  XXXXXXX_,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_004A[ 32] = { /* code 004A, LATIN CAPITAL LETTER J */
  __XXXXXX,X_______,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  X____X__,________,
  X___X___,________,
  _XXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_004B[ 26] = { /* code 004B, LATIN CAPITAL LETTER K */
  XXX__XXX,X_______,
  _X____X_,________,
  _X___X__,________,
  _X___X__,________,
  _X__X___,________,
  _X_XX___,________,
  _XX_X___,________,
  _X___X__,________,
  _X___X__,________,
  _X____X_,________,
  _X____X_,________,
  _X_____X,________,
  XXX___XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_004C[ 26] = { /* code 004C, LATIN CAPITAL LETTER L */
  XXX_____,________,
  _X______,________,
  _X______,________,
  _X______,________,
  _X______,________,
  _X______,________,
  _X______,________,
  _X______,________,
  _X______,________,
  _X______,________,
  _X______,X_______,
  _X_____X,________,
  XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_004D[ 26] = { /* code 004D, LATIN CAPITAL LETTER M */
  XXX___XX,X_______,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _X_X_X_X,________,
  _X_X_X_X,________,
  _X_X_X_X,________,
  _X_X_X_X,________,
  _X_X_X_X,________,
  _X__X__X,________,
  _X__X__X,________,
  _X__X__X,________,
  XXX_X_XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_004E[ 26] = { /* code 004E, LATIN CAPITAL LETTER N */
  XXX___XX,X_______,
  _XX____X,________,
  _X_X___X,________,
  _X_X___X,________,
  _X_X___X,________,
  _X__X__X,________,
  _X__X__X,________,
  _X___X_X,________,
  _X___X_X,________,
  _X____XX,________,
  _X____XX,________,
  _X____XX,________,
  XXX____X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_004F[ 26] = { /* code 004F, LATIN CAPITAL LETTER O */
  ___XXX__,________,
  _XX___XX,________,
  _X_____X,________,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  _X_____X,________,
  _XX___XX,________,
  ___XXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0050[ 26] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXXXX_,________,
  _X_____X,________,
  _X______,X_______,
  _X______,X_______,
  _X______,X_______,
  _X_____X,________,
  _XXXXXX_,________,
  _X______,________,
  _X______,________,
  _X______,________,
  _X______,________,
  _X______,________,
  XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0051[ 30] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ___XXX__,________,
  _XX___XX,________,
  _X_____X,________,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_XXX___,X_______,
  _X___X_X,________,
  _XX___XX,________,
  ___XXXX_,________,
  ______X_,X_______,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0052[ 26] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXXXX__,________,
  _X____X_,________,
  _X_____X,________,
  _X_____X,________,
  _X____X_,________,
  _XXXXX__,________,
  _X__X___,________,
  _X___X__,________,
  _X___X__,________,
  _X____X_,________,
  _X____X_,________,
  _X_____X,________,
  XXX____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0053[ 13] = { /* code 0053, LATIN CAPITAL LETTER S */
  __XXX_X_,
  _X___XX_,
  X_____X_,
  X_______,
  X_______,
  _XX_____,
  ___XX___,
  _____X__,
  ______X_,
  X_____X_,
  X_____X_,
  XX___X__,
  X_XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0054[ 26] = { /* code 0054, LATIN CAPITAL LETTER T */
  _XXXXXXX,________,
  X___X___,X_______,
  X___X___,X_______,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ___XXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0055[ 26] = { /* code 0055, LATIN CAPITAL LETTER U */
  XXX___XX,X_______,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________,
  __X___X_,________,
  ___XXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0056[ 26] = { /* code 0056, LATIN CAPITAL LETTER V */
  XXX___XX,X_______,
  _X_____X,________,
  _X_____X,________,
  __X___X_,________,
  __X___X_,________,
  __X___X_,________,
  __X___X_,________,
  ___X_X__,________,
  ___X_X__,________,
  ___X_X__,________,
  ____X___,________,
  ____X___,________,
  ____X___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0057[ 26] = { /* code 0057, LATIN CAPITAL LETTER W */
  XX_XXX_X,X_______,
  _X__X__X,________,
  _X__X__X,________,
  _X__X__X,________,
  _X__X__X,________,
  _X_X_X_X,________,
  _X_X_X_X,________,
  _X_X_X_X,________,
  _X_X_X_X,________,
  __X___X_,________,
  __X___X_,________,
  __X___X_,________,
  __X___X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0058[ 13] = { /* code 0058, LATIN CAPITAL LETTER X */
  XXX__XXX,
  _X____X_,
  __X__X__,
  __X__X__,
  __X_X___,
  ___XX___,
  ___X____,
  ___XX___,
  __X_X___,
  __X__X__,
  _X___X__,
  _X____X_,
  XXX__XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0059[ 26] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XXX___XX,X_______,
  _X_____X,________,
  _X_____X,________,
  __X___X_,________,
  __X___X_,________,
  ___X_X__,________,
  ___X_X__,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ___XXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_005A[ 13] = { /* code 005A, LATIN CAPITAL LETTER Z */
  _XXXXXXX,
  _X____X_,
  X_____X_,
  _____X__,
  _____X__,
  ____X___,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  _X_____X,
  _X____X_,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0061[ 18] = { /* code 0061, LATIN SMALL LETTER A */
  _XXXXX__,________,
  X_____X_,________,
  X_____X_,________,
  ____XXX_,________,
  _XXX__X_,________,
  X_____X_,________,
  X_____X_,________,
  X____XX_,X_______,
  _XXXX_XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0062[ 14] = { /* code 0062, LATIN SMALL LETTER B */
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  _X_XXX__,
  _XX___X_,
  _X_____X,
  _X_____X,
  _X_____X,
  _X_____X,
  _X_____X,
  _XX___X_,
  _X_XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0063[  9] = { /* code 0063, LATIN SMALL LETTER C */
  __XXXX__,
  _X____X_,
  X_____X_,
  X_______,
  X_______,
  X_______,
  X______X,
  _X____X_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0064[ 14] = { /* code 0064, LATIN SMALL LETTER D */
  ________,
  _____XX_,
  ______X_,
  ______X_,
  ______X_,
  __XXX_X_,
  _X___XX_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  _X___XX_,
  __XXX_XX};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0065[  9] = { /* code 0065, LATIN SMALL LETTER E */
  __XXXX__,
  _X____X_,
  X______X,
  X______X,
  XXXXXXXX,
  X_______,
  X______X,
  _X____X_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0066[ 13] = { /* code 0066, LATIN SMALL LETTER F */
  ___XXX__,
  __X___X_,
  __X_____,
  __X_____,
  XXXXXX__,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0067[ 12] = { /* code 0067, LATIN SMALL LETTER G */
  __XXXXXX,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  _X______,
  _XXXXXX_,
  X______X,
  X______X,
  X______X,
  _XXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0068[ 14] = { /* code 0068, LATIN SMALL LETTER H */
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  _X_XXX__,
  _XX___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  XXX__XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0069[ 13] = { /* code 0069, LATIN SMALL LETTER I */
  _XX_____,
  _XX_____,
  ________,
  ________,
  XXX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_006A[ 16] = { /* code 006A, LATIN SMALL LETTER J */
  ____XX__,
  ____XX__,
  ________,
  ________,
  ___XXX__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  X___X___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_006B[ 14] = { /* code 006B, LATIN SMALL LETTER K */
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  _X__XXX_,
  _X___X__,
  _X__X___,
  _X_X____,
  _XX_X___,
  _X__X___,
  _X___X__,
  _X____X_,
  XXX__XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_006C[ 14] = { /* code 006C, LATIN SMALL LETTER L */
  ___X____,
  XXXX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_006D[ 18] = { /* code 006D, LATIN SMALL LETTER M */
  XX_XXXX_,________,
  _XX_X__X,________,
  _X__X__X,________,
  _X__X__X,________,
  _X__X__X,________,
  _X__X__X,________,
  _X__X__X,________,
  _X__X__X,________,
  XXX_XX_X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_006E[  9] = { /* code 006E, LATIN SMALL LETTER N */
  XX_XXX__,
  _XX___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  XXX__XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_006F[  9] = { /* code 006F, LATIN SMALL LETTER O */
  __XXXX__,
  _X____X_,
  X______X,
  X______X,
  X______X,
  X______X,
  X______X,
  _X____X_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0070[ 12] = { /* code 0070, LATIN SMALL LETTER P */
  XX_XXX__,
  _XX___X_,
  _X_____X,
  _X_____X,
  _X_____X,
  _X_____X,
  _X_____X,
  _XX___X_,
  _X_XXX__,
  _X______,
  _X______,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0071[ 12] = { /* code 0071, LATIN SMALL LETTER Q */
  __XXX_X_,
  _X___XX_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  _X___XX_,
  __XXX_X_,
  ______X_,
  ______X_,
  _____XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0072[  9] = { /* code 0072, LATIN SMALL LETTER R */
  XXX__XXX,
  __X_X__X,
  __XX____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0073[  9] = { /* code 0073, LATIN SMALL LETTER S */
  _XXXX_X_,
  X____XX_,
  X_____X_,
  XX______,
  __XXX___,
  _____XX_,
  X_____X_,
  XX____X_,
  X_XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0074[ 12] = { /* code 0074, LATIN SMALL LETTER T */
  __X_____,
  __X_____,
  __X_____,
  XXXXXX__,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X___X_,
  ___XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0075[  9] = { /* code 0075, LATIN SMALL LETTER U */
  XX___XX_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___XX_,
  __XXX_XX};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0076[ 18] = { /* code 0076, LATIN SMALL LETTER V */
  XXX___XX,X_______,
  _X_____X,________,
  _X_____X,________,
  __X___X_,________,
  __X___X_,________,
  ___X_X__,________,
  ___X_X__,________,
  ____X___,________,
  ____X___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0077[ 18] = { /* code 0077, LATIN SMALL LETTER W */
  XX_XXX_X,X_______,
  _X__X__X,________,
  _X__X__X,________,
  _X__X__X,________,
  _X_X_X_X,________,
  _X_X_X_X,________,
  _X_X_X_X,________,
  __X___X_,________,
  __X___X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_0079[ 12] = { /* code 0079, LATIN SMALL LETTER Y */
  XXX__XXX,
  _X____X_,
  __X__X__,
  __X__X__,
  __X__X__,
  ___X_X__,
  ___XX___,
  ____X___,
  ____X___,
  ___X____,
  _X_X____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_007A[  9] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXXX_,
  X____X__,
  X___X___,
  ____X___,
  ___X____,
  __X____X,
  _X_____X,
  _X____X_,
  XXXXXXX_};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_4F4D[ 54] = { /* code 4F4D */
  ____X___,_X______,________,
  ____X___,__X_____,________,
  ____X___,__XX____,________,
  ___X____,___X____,________,
  ___X__XX,XXXXXXXX,X_______,
  __XX____,________,________,
  __XX____,______X_,________,
  _X_X___X,______X_,________,
  _X_X____,X____XX_,________,
  X__X____,X____X__,________,
  ___X____,X____X__,________,
  ___X____,XX___X__,________,
  ___X____,_X__X___,________,
  ___X____,_X__X___,________,
  ___X____,____X___,________,
  ___X____,____X___,________,
  ___X__XX,XXXXXXXX,XX______,
  ___X____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_505C[ 54] = { /* code 505C */
  ____X___,__X_____,________,
  ___XX___,__XX____,________,
  ___X__XX,XXXXXXXX,X_______,
  ___X____,________,________,
  __X____X,_XXXXXX_,________,
  __XX____,X_____X_,________,
  __X_____,XXXXXXX_,________,
  _XX____X,X_______,________,
  X_X__XXX,XXXXXXXX,X_______,
  __X__X__,________,X_______,
  __X_XX__,_______X,________,
  __X____X,XXX_XXXX,________,
  __X_____,___X____,________,
  __X_____,___X____,________,
  __X_____,___X____,________,
  __X_____,___X____,________,
  __X_____,XXXX____,________,
  __X_____,__X_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_52A8[ 54] = { /* code 52A8 */
  ________,____X___,________,
  ________,____X___,________,
  _XXXXXXX,____X___,________,
  ________,____X___,________,
  ________,__XXXXXX,X_______,
  ________,____X___,X_______,
  _XXX_XXX,X___X___,X_______,
  ____X___,___XX___,X_______,
  ___XX___,___X____,X_______,
  ___X____,___X____,X_______,
  __X___X_,___X____,X_______,
  __X____X,___X____,X_______,
  _X____XX,X_X_____,X_______,
  XXXXXX__,X_X_____,X_______,
  _X______,XX_____X,X_______,
  ________,X______X,________,
  _______X,_____XXX,________,
  ______X_,______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_538B[ 54] = { /* code 538B */
  ________,_______X,________,
  ___XXXXX,XXXXXXXX,X_______,
  ___X____,________,________,
  ___X____,_X______,________,
  ___X____,_X______,________,
  ___X____,_X______,________,
  ___X____,_X______,________,
  ___X____,_X______,________,
  ___X__XX,XXXXXXXX,________,
  ___X____,_X______,________,
  ___X____,_X______,________,
  __XX____,_X__XX__,________,
  __X_____,_X___XX_,________,
  __X_____,_X____X_,________,
  __X_____,_X____X_,________,
  _X______,_X______,X_______,
  _X_XXXXX,XXXXXXXX,XX______,
  X_______,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_53C2[ 54] = { /* code 53C2 */
  ________,X_______,________,
  _______X,________,________,
  _____XX_,____X___,________,
  ___XX___,__XXXXX_,________,
  ___XXXXX,XX____XX,________,
  _______X,________,________,
  _XXXXXXX,XX_XXXXX,XX______,
  ______X_,__X_____,________,
  _____X__,_X_X____,________,
  ____X___,XX__XX__,________,
  __XX__XX,___X__XX,X_______,
  _X___X__,__XXX___,X_______,
  X__XX___,_X______,________,
  _______X,X____XX_,________,
  ____XXX_,___XX___,________,
  __XX____,_XX_____,________,
  ______XX,X_______,________,
  __XXXX__,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_53D1[ 54] = { /* code 53D1 */
  _______X,___X____,________,
  _______X,____X___,________,
  ___X___X,_____X__,________,
  __XX___X,_____XX_,________,
  __X____X,________,________,
  _XXXXXXX,XXXXXXXX,X_______,
  ______X_,________,________,
  ______X_,________,________,
  ______X_,XXXXXXX_,________,
  _____X_X,_____XX_,________,
  _____X__,X____X__,________,
  _____X__,X___X___,________,
  ____X___,_X_XX___,________,
  ___XX___,__XX____,________,
  ___X____,_XXX____,________,
  __X_____,X___XX__,________,
  _X____XX,______XX,XX______,
  X___XX__,________,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_5668[ 51] = { /* code 5668 */
  ___XXXXX,__XXXXX_,________,
  ___X___X,__X___X_,________,
  ___X___X,__X___X_,________,
  ___X___X,__X___X_,________,
  ___XXXXX,__X_XXX_,________,
  ___X___X,__XX__X_,________,
  ________,XX__XX__,________,
  _XXXXX_X,XX_XXXXX,X_______,
  ______X_,__X_____,________,
  _____X__,___XX___,________,
  ____X___,_____XX_,________,
  _XXXXXXX,__XXXXXX,X_______,
  X__X___X,__X___X_,________,
  ___X___X,__X___X_,________,
  ___XXXXX,__XXXXX_,________,
  ___X___X,__X___X_,________,
  ________,__X___X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_5782[ 51] = { /* code 5782 */
  ________,____XX__,________,
  ____XXXX,XXXXXXX_,________,
  ________,_X______,________,
  ________,_X______,________,
  __XXX_XX,XXXX__XX,X_______,
  _____X__,_X__XX__,________,
  _____X__,_X__XX__,________,
  _____X__,_X__XX__,________,
  _XXXXXXX,XXXXXXXX,X_______,
  _____X__,_X__XX__,________,
  _____X__,_X__XX__,________,
  _____X__,_X__XX__,________,
  _XXXXXXX,XXXXXXXX,X_______,
  ________,_X______,________,
  ________,_X______,________,
  ________,_X_____X,________,
  ___XXXXX,XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_5B66[ 54] = { /* code 5B66 */
  _______X,_____X__,________,
  ____X___,X____XX_,________,
  ____XX__,XX___X__,________,
  ____XX__,XX__X___,________,
  _____X__,____X___,________,
  ___XXXXX,XXXXXXXX,X_______,
  __X_____,________,X_______,
  _XXXXXXX,XXXXXX_X,________,
  _X______,___XX___,________,
  ________,__X_____,________,
  ________,_X______,________,
  _XXXXXXX,XXXXXXXX,X_______,
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________,
  ______XX,XX______,________,
  ________,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_5E45[ 54] = { /* code 5E45 */
  __X_____,________,________,
  __X____X,XXXXXXXX,X_______,
  __X_____,________,________,
  XXXXXX__,XXXXXXX_,________,
  X_X__X__,X_____X_,________,
  X_X__X__,X_____X_,________,
  X_X__X__,XXXXXXX_,________,
  X_X__X__,X_____X_,________,
  X_X__X__,________,________,
  X_X__X_X,XXX_XXXX,________,
  X_X__X_X,___X___X,________,
  X_X__X_X,___X___X,________,
  X_XXXX_X,XXXXXXXX,________,
  __X____X,___X___X,________,
  __X____X,___X___X,________,
  __X____X,XXXXXXXX,________,
  __X____X,_______X,________,
  __X____X,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_5E73[ 54] = { /* code 5E73 */
  ________,_______X,________,
  __XXXXXX,__XXXXXX,________,
  ________,XX______,________,
  ___X____,XX____X_,________,
  ____X___,XX___XX_,________,
  ____XX__,XX___X__,________,
  _____X__,XX__X___,________,
  _____X__,XX_X____,X_______,
  _XXXXXXX,XXXXXXXX,XX______,
  ________,XX______,________,
  ________,XX______,________,
  ________,XX______,________,
  ________,XX______,________,
  ________,XX______,________,
  ________,XX______,________,
  ________,XX______,________,
  ________,XX______,________,
  ________,XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_5EA6[ 54] = { /* code 5EA6 */
  ________,X_______,________,
  ________,_XX_____,________,
  __XXXXX_,XXXX_XXX,X_______,
  __X____X,____X___,________,
  __X____X,____X___,________,
  __XXXXXX,XXXXXXXX,X_______,
  __X____X,____X___,________,
  __X____X,____X___,________,
  __X____X,XXXXX___,________,
  __X____X,____X___,________,
  __X___X_,XXXXXXX_,________,
  __X____X,_____X__,________,
  __X_____,X___X___,________,
  _X______,_X_X____,________,
  _X______,__X_____,________,
  _X______,XX_XX___,________,
  X_____XX,____XXXX,XX______,
  ___XXX__,_______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_5F62[ 54] = { /* code 5F62 */
  ________,_______X,________,
  __XX_XXX,_XX___XX,________,
  ____X___,X_____X_,________,
  ____X___,X____X__,________,
  ____X___,X___X___,________,
  ____X___,X__X____,________,
  ____X___,X______X,X_______,
  _XXXXXXX,XXX____X,________,
  ____X___,X_____X_,________,
  ___XX___,X____X__,________,
  ___X____,X__XX___,________,
  ___X____,X_X_____,X_______,
  ___X____,X______X,X_______,
  ___X___X,X_____XX,________,
  __X____X,X____XX_,________,
  __X____X,X___XX__,________,
  _X_____X,X_XX____,________,
  X_______,_X______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_6001[ 51] = { /* code 6001 */
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  _XXXXXX_,X_XXXXXX,X_______,
  _______X,XX______,________,
  _______X,__X_____,________,
  ______XX,__X_____,________,
  ______X_,___X____,________,
  _____X_X,X___XX__,________,
  ___XX___,XX___XXX,XX______,
  _XX_____,_X_____X,X_______,
  _____XXX,X_______,________,
  _____X__,XX____X_,________,
  __X__X__,_X__X__X,________,
  __X__X__,____X__X,X_______,
  _XX__X__,____X___,X_______,
  _____XXX,XXXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_626B[ 54] = { /* code 626B */
  ____X___,________,________,
  ____X___,________,________,
  ____X___,________,________,
  ____X___,XXXXXXXX,X_______,
  _XXXXXXX,________,X_______,
  ____X___,________,X_______,
  ____X___,________,X_______,
  ____X__X,________,X_______,
  ____XXX_,_XXXXXXX,X_______,
  __XXX___,________,X_______,
  XX__X___,________,X_______,
  ____X___,________,X_______,
  ____X___,________,X_______,
  ____X___,________,X_______,
  ____X___,________,X_______,
  ____X___,XXXXXXXX,X_______,
  __XXX___,________,X_______,
  ___X____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_63CF[ 54] = { /* code 63CF */
  ___X____,_X___X__,________,
  ___X____,__X__X__,________,
  ___X____,__X__X__,________,
  ___X___X,XXXXXXXX,X_______,
  _XXXXXX_,__X__X__,________,
  ___X____,__X__X__,________,
  ___X____,_XX__X__,________,
  ___X____,________,________,
  ___X_XXX,_XXX_XXX,X_______,
  ___XX__X,X___X___,X_______,
  XXXX____,X___X___,X_______,
  ___X____,XXXXXXXX,X_______,
  ___X____,X___X___,X_______,
  ___X____,X___X___,X_______,
  ___X____,X___X___,X_______,
  ___X___X,XXXXXXXX,X_______,
  _XXX___X,X_______,X_______,
  ___X___X,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_6570[ 54] = { /* code 6570 */
  _____X__,____X___,________,
  _X___X__,X__XX___,________,
  __XX_X__,X__X____,________,
  ___X_X_X,___X____,________,
  _XXX_XXX,XXXXXXX_,XX______,
  ____XX__,__X____X,________,
  ___X_XXX,__X____X,________,
  __X__X__,XX_X__XX,________,
  _X___X__,_X_X__X_,________,
  ____XX__,___X__X_,________,
  _XXXXXX_,X__X__X_,________,
  ____X__X,____X_X_,________,
  ___X___X,____XX__,________,
  ____XXX_,____XX__,________,
  _____X_X,X___XXX_,________,
  ___XX___,X_XX__XX,________,
  _XX_____,_X_____X,XX______,
  _______X,X_______,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_663E[ 48] = { /* code 663E */
  ____XXXX,XXXXXX__,________,
  ____X___,_____X__,________,
  ____X___,_____X__,________,
  ____XXXX,XXXXXX__,________,
  ____X___,_____X__,________,
  ____X___,_____X__,________,
  ____XXXX,XXXXXX__,________,
  ____X___,_____X__,________,
  ______X_,__X_____,________,
  _X____X_,__XX___X,________,
  __X___X_,__X___XX,________,
  ___X__X_,__X___X_,________,
  ___XX_X_,__X__X__,________,
  ____X_X_,__X_X___,________,
  ______X_,__XX____,________,
  _XXXXXXX,XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_6682[ 54] = { /* code 6682 */
  ____X___,________,________,
  ____X___,__X_XXXX,X_______,
  _XX_X_XX,XX_X____,________,
  ___X_X__,___X____,________,
  ___X__X_,___XXX_X,XX______,
  __XXXXXX,XX_X__X_,________,
  ______X_,__X___X_,________,
  _____XXX,XXX___X_,________,
  _XXXX_X_,__X___X_,________,
  ______X_,XX____X_,________,
  ____XXXX,XXXXXXX_,________,
  ____X___,______X_,________,
  ____X___,______X_,________,
  ____XXXX,XXXXXXX_,________,
  ____X___,______X_,________,
  ____X___,______X_,________,
  ____XXXX,XXXXXXX_,________,
  ____X___,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_6807[ 54] = { /* code 6807 */
  ___X____,________,________,
  ___X____,________,________,
  ___X____,_XXXXXXX,________,
  ___X____,________,________,
  _XXXXXX_,________,________,
  ___X____,________,________,
  ___X___X,XXXX_XXX,XX______,
  __XXX___,____X___,________,
  __XX_X__,____X___,________,
  __XX__X_,____X___,________,
  _X_X____,XX__X_X_,________,
  _X_X____,X___X__X,________,
  X__X___X,____X__X,X_______,
  ___X___X,____X___,X_______,
  ___X__X_,____X___,X_______,
  ___X_X__,____X___,________,
  ___X____,_XXXX___,________,
  ___X____,___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_6837[ 54] = { /* code 6837 */
  ___X____,______X_,________,
  ___X____,XX____X_,________,
  ___X____,_XX__X__,________,
  ___X____,__X__X__,________,
  _XXXXXXX,XXX_XXXX,X_______,
  ___X____,___X____,________,
  ___X____,___X____,________,
  __XXX___,XXXXXXXX,________,
  __XX_X__,___X____,________,
  __XX__X_,___X____,________,
  _X_X____,___X____,________,
  _X_X___X,XXXXXXXX,X_______,
  X__X____,___X____,________,
  ___X____,___X____,________,
  ___X____,___X____,________,
  ___X____,___X____,________,
  ___X____,___X____,________,
  ___X____,___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_6B65[ 54] = { /* code 6B65 */
  ________,_X______,________,
  ________,_X______,________,
  ____X___,_X______,________,
  ____X___,_XXXXXXX,________,
  ____X___,_X______,________,
  ____X___,_X______,________,
  _XXXXXXX,XXXXXXXX,X_______,
  ________,_X______,________,
  ________,_X______,________,
  ____XX__,_X_____X,________,
  ____X___,_X____XX,________,
  ___X____,_X___XX_,________,
  ___X____,_X__XX__,________,
  __X_____,_X_XX___,________,
  _X______,_XX_____,________,
  _______X,X_______,________,
  ____XXX_,________,________,
  _XXX____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_6C34[ 54] = { /* code 6C34 */
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,XX______,________,
  ________,XX____XX,________,
  _XXXXXX_,XX___XX_,________,
  _____XX_,X_X_X___,________,
  _____X__,X_XX____,________,
  _____X__,X__X____,________,
  ____XX__,X__X____,________,
  ____X___,X___X___,________,
  ___X____,X___XX__,________,
  ___X____,X____X__,________,
  __X_____,X_____XX,________,
  _X______,X_____XX,X_______,
  X_______,X_______,X_______,
  ______XX,X_______,________,
  _______X,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_6CE2[ 54] = { /* code 6CE2 */
  ________,___XX___,________,
  __XX____,___X____,________,
  ___X____,___X____,________,
  _______X,XXXXXXXX,X_______,
  _______X,___X___X,________,
  XX___X_X,___X____,________,
  _X__X__X,___X____,________,
  _XX_X__X,___X____,________,
  ____X__X,X_XXXX_X,________,
  ___X___X,_X____XX,________,
  ___X__XX,_X____X_,________,
  __X___X_,__X__XX_,________,
  XXX___X_,__X__X__,________,
  __X___X_,___XX___,________,
  __X__X__,___XXX__,________,
  _XX__X__,_XX__XX_,________,
  _XX_X___,X_____XX,XX______,
  ___X__XX,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_6D4B[ 54] = { /* code 6D4B */
  _X______,________,X_______,
  __XX_XXX,XXX_____,X_______,
  ___X_X__,__X_____,X_______,
  _____X__,__X__X__,X_______,
  _____X__,X_X__X__,X_______,
  _X__XX__,X_X__X__,X_______,
  _X__XX__,X_X__X__,X_______,
  ____XX__,X_X__X__,X_______,
  ___X_X__,X_X__X__,X_______,
  ___X_X__,X_X__X__,X_______,
  ___X_X__,X_X__X__,X_______,
  __X__X_X,__X__X__,X_______,
  XXX__X_X,__X__X__,X_______,
  __X____X,________,X_______,
  __X___X_,_X______,X_______,
  _XX___X_,__X_____,X_______,
  _XX_XX__,__XX__XX,X_______,
  ___X____,_______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_6D4F[ 54] = { /* code 6D4F */
  _______X,________,X_______,
  __XX____,X_______,X_______,
  ___XX___,X_______,X_______,
  ___X____,X____X__,X_______,
  _____XXX,XXXXXX__,X_______,
  X___X___,__X__X__,X_______,
  _X__XX__,_X___X__,X_______,
  __X_X_X_,_X___X__,X_______,
  ___X__X_,_X___X__,X_______,
  ___X___X,_X___X__,X_______,
  ___X____,X____X__,X_______,
  ___X____,X____X__,X_______,
  XXX____X,_X___X__,X_______,
  __X____X,_XX__X__,X_______,
  __X___X_,__X_____,X_______,
  __X__X__,__X_____,X_______,
  __X_X___,______XX,X_______,
  ________,_______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_6E38[ 54] = { /* code 6E38 */
  ________,____X___,________,
  __X___XX,____X___,________,
  ___X___X,____X___,________,
  _______X,___XXXXX,X_______,
  ____XX_X,XX_X____,________,
  XX__X_X_,__XXXXX_,X_______,
  _X_X__X_,__X____X,________,
  _X_X__XX,XX____X_,________,
  ___X__X_,_X___XX_,________,
  ___X__X_,_X____X_,________,
  __X___X_,_XXXXXXX,XX______,
  __X___X_,_X____X_,________,
  _XX__X__,_X____X_,________,
  _XX__X__,_X____X_,________,
  _XX_X___,X_____X_,________,
  _XX_X___,X_____X_,________,
  __XX___X,X___XX__,________,
  __X_____,_____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_6EE4[ 54] = { /* code 6EE4 */
  ________,___X____,________,
  __X_____,___X____,________,
  ___X____,___XXXXX,________,
  ___X____,___X____,________,
  _____XXX,XXXXXXXX,X_______,
  X____XX_,___X____,X_______,
  _X__X_X_,___X_XXX,________,
  _XX_X_X_,XXXXX__X,________,
  ____X_X_,___X___X,________,
  ___X__X_,___XXXXX,X_______,
  ___X__X_,________,________,
  ___X__X_,____X___,________,
  __X___X_,X_X__X_X,________,
  _XX___X_,X_X____X,X_______,
  __X__X_X,X_X____X,_X______,
  __X__X_X,__X____X,________,
  _XX_X___,__XXXXXX,________,
  __XX____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_72B6[ 54] = { /* code 72B6 */
  ____XX__,__X_____,________,
  ____XX__,__XX_X__,________,
  ____XX__,__XX__XX,________,
  X___XX__,__XX___X,________,
  _X__XX__,__XX___X,________,
  __X_XX__,__XX____,X_______,
  __X_XXXX,XXXX_XXX,X_______,
  ____XX__,__X_X___,________,
  ____XX__,__X_X___,________,
  ___XXX__,__X_X___,________,
  __X_XX__,__X_X___,________,
  _X__XX__,__X__X__,________,
  XX__XX__,_X___X__,________,
  ____XX__,_X____X_,________,
  ____XX__,X_____XX,________,
  ____XX__,X______X,X_______,
  ____XX_X,_______X,XX______,
  ____X_X_,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_7387[ 54] = { /* code 7387 */
  ________,X_______,________,
  ________,XX______,________,
  __XXXXXX,XXXXXXXX,X_______,
  ________,X_______,________,
  __X____X,______X_,________,
  ___X__X_,__XX_XX_,________,
  _____XXX,XX__X___,________,
  ________,X_______,________,
  ____X__X,__X__X__,________,
  __XX__X_,_XXX__XX,________,
  _X____XX,X_______,________,
  ________,X_______,________,
  _XXXXXXX,XXXXXXXX,XX______,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_7535[ 34] = { /* code 7535 */
  ______X_,________,
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXX___,
  X_____X_,____X___,
  X_____X_,____X___,
  X_____X_,____X___,
  XXXXXXXX,XXXXX___,
  X_____X_,____X___,
  X_____X_,____X___,
  X_____X_,____X___,
  XXXXXXXX,XXXXX___,
  X_____X_,____X_X_,
  ______X_,______X_,
  ______X_,______X_,
  ______X_,______X_,
  ______XX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_754C[ 54] = { /* code 754C */
  ___XXXXX,X_XXXXX_,________,
  ___X____,_X____X_,________,
  ___X____,_X____X_,________,
  ___XXXXX,XXXXXXX_,________,
  ___X____,_X____X_,________,
  ___X____,_X____X_,________,
  ___XXXX_,_X_XXXX_,________,
  ___X___X,X_X_____,________,
  _______X,___X____,________,
  ______X_,____XX__,________,
  ____XXXX,___XXXXX,X_______,
  __XX__XX,___X___X,X_______,
  XX____X_,___X____,________,
  ______X_,___X____,________,
  _____XX_,___X____,________,
  _____X__,___X____,________,
  ___XX___,___X____,________,
  __X_____,___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_76F4[ 51] = { /* code 76F4 */
  ________,_X______,________,
  ________,XX______,________,
  __XXXXXX,XXXXXXXX,X_______,
  ________,X_______,________,
  ________,X_______,________,
  ____XXXX,XXXXXXX_,________,
  ____X___,_____X__,________,
  ____XXXX,XXXXXX__,________,
  ____X___,_____X__,________,
  ____X___,_____X__,________,
  ____XXXX,XXXXXX__,________,
  ____X___,_____X__,________,
  ____X___,_____X__,________,
  ____XXXX,XXXXXX__,________,
  ____X___,_____X__,________,
  ____X___,_____X__,X_______,
  _XXXXXXX,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_793A[ 54] = { /* code 793A */
  ________,______X_,________,
  ___XXXXX,XXXXXXXX,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,X_______,
  _XXXXXXX,__XXXXXX,XX______,
  ________,XX______,________,
  ________,XX______,________,
  ____XX__,XX__X___,________,
  ____XX__,XX___X__,________,
  ___XX___,XX____X_,________,
  ___X____,XX____XX,________,
  __X_____,XX_____X,X_______,
  _X______,XX______,X_______,
  X_______,XX______,X_______,
  ______XX,XX______,________,
  _______X,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_79FB[ 54] = { /* code 79FB */
  ______X_,___X____,________,
  ___XXXX_,___X____,________,
  XXX_X___,__XXXXXX,X_______,
  ____X___,_XX____X,________,
  ____X___,X__X__X_,________,
  _XXXXXXX,___X_X__,________,
  ____X___,____X___,________,
  ___XX___,___X____,________,
  ___XXX__,_XX__X__,________,
  __X_X_X_,X___XX__,________,
  __X_X_X_,___XXXXX,X_______,
  _X__X___,__X_____,X_______,
  _X__X___,_XX____X,________,
  X___X___,X__X__X_,________,
  ____X___,___X_XX_,________,
  ____X___,___XX___,________,
  ____X___,_XX_____,________,
  ____XXXX,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_7F6E[ 51] = { /* code 7F6E */
  __XXXXXX,XXXXXXXX,________,
  __X___XX,___X___X,________,
  __X___XX,___X___X,________,
  __XXXXXX,XXXXXXXX,________,
  __X_____,________,________,
  ________,XX______,________,
  _XXXXXXX,XXXXXXXX,________,
  ________,X_______,________,
  ____XXXX,XXXXXXX_,________,
  ____X___,_____X__,________,
  ____XXXX,XXXXXX__,________,
  ____X___,_____X__,________,
  ____XXXX,XXXXXX__,________,
  ____X___,_____X__,________,
  ____XXXX,XXXXXX__,________,
  ____X___,_____X__,________,
  XXXXXXXX,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_81EA[ 36] = { /* code 81EA */
  _____X__,________,
  ____XX__,________,
  ____X___,________,
  XXXXXXXX,XXXX____,
  X_______,___X____,
  X_______,___X____,
  X_______,___X____,
  XXXXXXXX,XXXX____,
  X_______,___X____,
  X_______,___X____,
  X_______,___X____,
  XXXXXXXX,XXXX____,
  X_______,___X____,
  X_______,___X____,
  X_______,___X____,
  XXXXXXXX,XXXX____,
  X_______,___X____,
  X_______,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_85CF[ 54] = { /* code 85CF */
  ______XX,__XX____,________,
  _XXXXXXX,XXXXX_XX,X_______,
  ______X_,__X__X__,________,
  ______X_,__X_XXX_,________,
  _X______,____X__X,________,
  _X__XXXX,XXXXXXXX,X_______,
  _X__X___,____X___,________,
  _XXXX_XX,_XXXX__X,________,
  _X__X_X_,X___X__X,________,
  ____X_XX,XXXXX__X,________,
  _X_XX_X_,__X_X_X_,________,
  __X_X_XX,_XX__XX_,________,
  _X__X_X_,X____XX_,________,
  _X__X_X_,X____X__,________,
  _X_X__XX,XXXXX_X_,_X______,
  X__X__X_,___X___X,_X______,
  __X_____,_XX_____,XX______,
  _X______,X_______,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_884C[ 54] = { /* code 884C */
  ____X___,________,________,
  ____X___,_XXXXXXX,________,
  ___X____,________,________,
  ___X____,________,________,
  __X__X__,________,________,
  _X___X__,________,________,
  ____X__X,XXXX_XXX,XX______,
  ___XX___,____X___,________,
  ___XX___,____X___,________,
  __X_X___,____X___,________,
  _X__X___,____X___,________,
  X___X___,____X___,________,
  ____X___,____X___,________,
  ____X___,____X___,________,
  ____X___,____X___,________,
  ____X___,____X___,________,
  ____X___,__XXX___,________,
  ____X___,___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_8868[ 54] = { /* code 8868 */
  ________,X_______,________,
  ________,X_______,________,
  __XXXXXX,XXXXXXXX,________,
  ________,X_______,________,
  ____XXXX,XXXXXXX_,________,
  ________,X_______,________,
  ________,X_______,________,
  _XXXXXX_,XXXXXX_X,X_______,
  _______X,X_____X_,________,
  _______X,_X____X_,________,
  ______X_,_X___X__,________,
  _____X__,__XXX___,________,
  ___XXX__,___X____,________,
  _XX__X__,___XX___,________,
  X____X__,_X__XX__,________,
  _____X__,X____XXX,X_______,
  _____XXX,_______X,X_______,
  _____X__,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_89C8[ 54] = { /* code 89C8 */
  ______X_,___X____,________,
  __X___X_,___X____,________,
  __X___X_,__XXXXXX,X_______,
  __X___X_,__X_____,________,
  __X___X_,_X__XX__,________,
  __X___X_,_X____X_,________,
  ______X_,X_____X_,________,
  ____XXXX,XXXXXXX_,________,
  ____X___,_____X__,________,
  ____X___,X____X__,________,
  ____X___,XX___X__,________,
  ____X___,XX___X__,________,
  ____X___,XXX__X__,________,
  ____X___,XX______,________,
  _______X,_X______,X_______,
  ______X_,_X______,X_______,
  ____XX__,__XXXXXX,XX______,
  _XXX____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_89E6[ 54] = { /* code 89E6 */
  ___XX___,________,________,
  ___X____,_____X__,________,
  ___XXXX_,_____X__,________,
  __X___X_,_____X__,________,
  __X__X__,_____X__,________,
  _XXX_XXX,__XXXXXX,X_______,
  X_X_X__X,__X__X__,X_______,
  __X_X__X,__X__X__,X_______,
  __XXXXXX,__X__X__,X_______,
  __X_X__X,__X__X__,X_______,
  __X_X__X,__XXXXXX,X_______,
  __XXXXXX,__X__X__,X_______,
  __X_X__X,_____X__,________,
  _X__X__X,_____X_X,________,
  _X__X__X,_____X__,X_______,
  _X__X__X,_XXXXXXX,_X______,
  X___X_XX,_X______,_X______,
  _______X,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_8BBE[ 54] = { /* code 8BBE */
  __X_____,X_XXXX__,________,
  ___X____,XX___X__,________,
  ___XX___,XX___X__,________,
  ________,X____X__,________,
  ________,X____X__,________,
  ________,X____XXX,XX______,
  _XXXX__X,________,________,
  ___X__X_,_XXXXXX_,________,
  ___X____,X_____X_,________,
  ___X____,_X___XX_,________,
  ___X____,_X___X__,________,
  ___X____,__X_XX__,________,
  ___X__X_,__X_X___,________,
  ___X_X__,___XX___,________,
  ___XX___,__XXX___,________,
  ___XX___,_XX__XX_,________,
  _______X,X_____XX,XX______,
  _____XX_,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_8FD0[ 51] = { /* code 8FD0 */
  __X_____,________,________,
  ___X____,XXXXXXX_,________,
  ___X____,________,________,
  ___X____,________,________,
  ________,________,________,
  ______XX,XX_XXXXX,X_______,
  _XXX____,__X_____,________,
  ___X____,__X_____,________,
  ___X____,_X______,________,
  ___X____,X____X__,________,
  ___X____,X_____X_,________,
  ___X___X,___XXXXX,________,
  ___X___X,XXX____X,________,
  ___X____,________,________,
  _XX_X___,________,________,
  XX___XXX,________,_X______,
  ________,XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_8FDB[ 51] = { /* code 8FDB */
  ________,_X___X__,________,
  __X_____,_X___X__,________,
  ___X____,_X___X__,________,
  ___X____,_X___X__,________,
  ______XX,XXXXXXXX,X_______,
  ________,_X___X__,________,
  _XXX____,_X___X__,________,
  ___X____,_X___X__,________,
  ___X__XX,XXXXXXXX,X_______,
  ___X____,_X___X__,________,
  ___X____,X____X__,________,
  ___X____,X____X__,________,
  ___X___X,_____X__,________,
  ___X__XX,_____X__,________,
  __X_XX__,_____X__,________,
  XX___XXX,________,_X______,
  _______X,XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_91C7[ 54] = { /* code 91C7 */
  ________,______XX,________,
  _______X,XXXXXXXX,________,
  __XXXXX_,______X_,________,
  ________,X_____XX,________,
  ___X____,XX___X__,________,
  ____X___,_X___X__,________,
  ____X___,X___X___,________,
  ________,XX_X____,________,
  _XXXXXX_,XX_XXXXX,XX______,
  _______X,X_X_____,________,
  ______XX,X_X_____,________,
  ______X_,X__X____,________,
  _____X__,X__X____,________,
  ____X___,X___X___,________,
  ___X____,X____XX_,________,
  __X_____,X_____XX,________,
  XX______,XX_____X,X_______,
  ________,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_91CF[ 51] = { /* code 91CF */
  ___XXXXX,XXXXXX__,________,
  ____X___,_____X__,________,
  ____XXXX,XXXXXX__,________,
  ____X___,_____X__,________,
  ____XXXX,XXXXXX__,________,
  ___XX___,_____X__,________,
  _XX_XXXX,XXXXX__X,XX______,
  ___XXXXX,_XXXXXX_,________,
  ___X____,X____X__,________,
  ___X____,X____X__,________,
  ___XXXXX,XXXXXX__,________,
  ___X____,X____X__,________,
  ___XXXXX,XXXXXXX_,________,
  ___X____,X____X__,________,
  ___XXXXX,XXXXXXXX,________,
  ________,X_______,________,
  _XXXXXXX,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_9636[ 54] = { /* code 9636 */
  ________,________,________,
  XXXXX___,_XX_____,________,
  X___X___,_XX_____,________,
  X__X____,X__X____,________,
  X__X___X,X___X___,________,
  X_X____X,_____X__,________,
  X_X___X_,______XX,________,
  X__XXX__,X___X__X,________,
  X__X____,X___X___,________,
  X___X___,X___X___,________,
  X___X___,X___X___,________,
  X___X___,X___X___,________,
  XXXXX__X,____X___,________,
  X_X____X,____X___,________,
  X______X,____X___,________,
  X_____X_,____X___,________,
  X____X__,____X___,________,
  X___X___,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_9690[ 54] = { /* code 9690 */
  ________,_X______,________,
  XXXXX___,XX______,________,
  X___X___,XXXXXX__,________,
  X__X___X,____X___,________,
  X__X___X,___X____,________,
  X__X__XX,XXXXXXXX,________,
  X_X__X__,______X_,________,
  X__X___X,XXXXXXX_,________,
  X___X___,______X_,________,
  X___X___,______X_,________,
  X___X__X,X_XXXXX_,________,
  X___X___,_X____X_,________,
  X__XX___,X_XX__X_,________,
  X_______,X__X_X_X,________,
  X____X__,X____X_X,X_______,
  X___XX__,X____X__,X_______,
  X_______,XXXXXX__,________,
  X_______,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_9762[ 54] = { /* code 9762 */
  ________,________,X_______,
  _XXXXXX_,__XXXXXX,XX______,
  _______X,XX______,________,
  _______X,________,________,
  __XXXXXX,XXX_XXXX,________,
  __X___X_,___X___X,________,
  __X___X_,___X___X,________,
  __X___X_,___X___X,________,
  __X___XX,XXXX___X,________,
  __X___X_,___X___X,________,
  __X___X_,___X___X,________,
  __X___XX,XXXX___X,________,
  __X___X_,___X___X,________,
  __X___X_,___X___X,________,
  __X___X_,___X___X,________,
  __XXXXXX,XXXXXXXX,________,
  __X_____,_______X,________,
  __X_____,_______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong20_9891[ 54] = { /* code 9891 */
  _____X__,________,________,
  _____X__,_XXX__XX,XX______,
  _____X__,____XX__,________,
  __XX_XXX,____X___,________,
  __X__X__,__XXXXXX,X_______,
  __X__X__,__X_____,X_______,
  __X__X__,__X_____,X_______,
  _XXX_XXX,X_X__X__,X_______,
  ____XX__,__X__X__,X_______,
  ____X___,__X__X__,X_______,
  __XXX__X,X_X__X__,X_______,
  __X_X__X,__X__X__,X_______,
  _X__X_XX,__X__X__,X_______,
  X___X_X_,____X___,________,
  _____X__,____X_X_,________,
  ____X___,___X___X,X_______,
  __XX____,_XX_____,XX______,
  _X______,X_______,_X______};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontFontSong20_CharInfo[114] = {
   {   1,   1,   0,  17,  10, acGUI_FontFontSong20_0020 } /* code 0020, SPACE */
  ,{   8,  17,   1,   1,  10, acGUI_FontFontSong20_002F } /* code 002F, SOLIDUS */
  ,{   8,  14,   1,   3,  10, acGUI_FontFontSong20_0030 } /* code 0030, DIGIT ZERO */
  ,{   5,  14,   3,   3,  10, acGUI_FontFontSong20_0031 } /* code 0031, DIGIT ONE */
  ,{   8,  14,   1,   3,  10, acGUI_FontFontSong20_0032 } /* code 0032, DIGIT TWO */
  ,{   8,  14,   1,   3,  10, acGUI_FontFontSong20_0033 } /* code 0033, DIGIT THREE */
  ,{   8,  14,   1,   3,  10, acGUI_FontFontSong20_0034 } /* code 0034, DIGIT FOUR */
  ,{   8,  14,   1,   3,  10, acGUI_FontFontSong20_0035 } /* code 0035, DIGIT FIVE */
  ,{   8,  14,   1,   3,  10, acGUI_FontFontSong20_0036 } /* code 0036, DIGIT SIX */
  ,{   8,  14,   1,   3,  10, acGUI_FontFontSong20_0037 } /* code 0037, DIGIT SEVEN */
  ,{   8,  14,   1,   3,  10, acGUI_FontFontSong20_0038 } /* code 0038, DIGIT EIGHT */
  ,{   8,  14,   1,   3,  10, acGUI_FontFontSong20_0039 } /* code 0039, DIGIT NINE */
  ,{   9,  13,   0,   4,  10, acGUI_FontFontSong20_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{   8,  13,   0,   4,  10, acGUI_FontFontSong20_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{   9,  13,   0,   4,  10, acGUI_FontFontSong20_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{   9,  13,   0,   4,  10, acGUI_FontFontSong20_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   9,  13,   0,   4,  10, acGUI_FontFontSong20_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   9,  13,   0,   4,  10, acGUI_FontFontSong20_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{   9,  13,   1,   4,  10, acGUI_FontFontSong20_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{   9,  13,   0,   4,  10, acGUI_FontFontSong20_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   7,  13,   1,   4,  10, acGUI_FontFontSong20_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   9,  16,   0,   4,  10, acGUI_FontFontSong20_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{   9,  13,   0,   4,  10, acGUI_FontFontSong20_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   9,  13,   0,   4,  10, acGUI_FontFontSong20_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{   9,  13,   0,   4,  10, acGUI_FontFontSong20_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{   9,  13,   0,   4,  10, acGUI_FontFontSong20_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{   9,  13,   0,   4,  10, acGUI_FontFontSong20_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{   9,  13,   0,   4,  10, acGUI_FontFontSong20_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{   9,  15,   0,   4,  10, acGUI_FontFontSong20_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{   9,  13,   0,   4,  10, acGUI_FontFontSong20_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{   7,  13,   1,   4,  10, acGUI_FontFontSong20_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{   9,  13,   0,   4,  10, acGUI_FontFontSong20_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{   9,  13,   0,   4,  10, acGUI_FontFontSong20_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{   9,  13,   0,   4,  10, acGUI_FontFontSong20_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{   9,  13,   0,   4,  10, acGUI_FontFontSong20_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{   8,  13,   1,   4,  10, acGUI_FontFontSong20_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{   9,  13,   0,   4,  10, acGUI_FontFontSong20_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{   8,  13,   1,   4,  10, acGUI_FontFontSong20_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   9,   9,   1,   8,  10, acGUI_FontFontSong20_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{   8,  14,   1,   3,  10, acGUI_FontFontSong20_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   8,   9,   1,   8,  10, acGUI_FontFontSong20_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{   8,  14,   1,   3,  10, acGUI_FontFontSong20_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   8,   9,   1,   8,  10, acGUI_FontFontSong20_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   7,  13,   2,   4,  10, acGUI_FontFontSong20_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{   8,  12,   1,   8,  10, acGUI_FontFontSong20_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{   8,  14,   1,   3,  10, acGUI_FontFontSong20_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   5,  13,   2,   4,  10, acGUI_FontFontSong20_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   6,  16,   2,   4,  10, acGUI_FontFontSong20_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{   8,  14,   1,   3,  10, acGUI_FontFontSong20_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   7,  14,   1,   3,  10, acGUI_FontFontSong20_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{   9,   9,   0,   8,  10, acGUI_FontFontSong20_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{   8,   9,   1,   8,  10, acGUI_FontFontSong20_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{   8,   9,   1,   8,  10, acGUI_FontFontSong20_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{   8,  12,   1,   8,  10, acGUI_FontFontSong20_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{   8,  12,   1,   8,  10, acGUI_FontFontSong20_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   8,   9,   1,   8,  10, acGUI_FontFontSong20_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   7,   9,   1,   8,  10, acGUI_FontFontSong20_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   7,  12,   2,   5,  10, acGUI_FontFontSong20_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{   8,   9,   1,   8,  10, acGUI_FontFontSong20_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{   9,   9,   0,   8,  10, acGUI_FontFontSong20_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{   9,   9,   0,   8,  10, acGUI_FontFontSong20_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{   8,  12,   1,   8,  10, acGUI_FontFontSong20_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   8,   9,   1,   8,  10, acGUI_FontFontSong20_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_4F4D } /* code 4F4D */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_505C } /* code 505C */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_52A8 } /* code 52A8 */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_538B } /* code 538B */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_53C2 } /* code 53C2 */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_53D1 } /* code 53D1 */
  ,{  18,  17,   1,   1,  20, acGUI_FontFontSong20_5668 } /* code 5668 */
  ,{  18,  17,   1,   1,  20, acGUI_FontFontSong20_5782 } /* code 5782 */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_5B66 } /* code 5B66 */
  ,{  17,  18,   2,   1,  20, acGUI_FontFontSong20_5E45 } /* code 5E45 */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_5E73 } /* code 5E73 */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_5EA6 } /* code 5EA6 */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_5F62 } /* code 5F62 */
  ,{  18,  17,   1,   1,  20, acGUI_FontFontSong20_6001 } /* code 6001 */
  ,{  17,  18,   1,   1,  20, acGUI_FontFontSong20_626B } /* code 626B */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_63CF } /* code 63CF */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_6570 } /* code 6570 */
  ,{  18,  16,   1,   1,  20, acGUI_FontFontSong20_663E } /* code 663E */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_6682 } /* code 6682 */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_6807 } /* code 6807 */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_6837 } /* code 6837 */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_6B65 } /* code 6B65 */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_6C34 } /* code 6C34 */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_6CE2 } /* code 6CE2 */
  ,{  17,  18,   1,   1,  20, acGUI_FontFontSong20_6D4B } /* code 6D4B */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_6D4F } /* code 6D4F */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_6E38 } /* code 6E38 */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_6EE4 } /* code 6EE4 */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_72B6 } /* code 72B6 */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_7387 } /* code 7387 */
  ,{  16,  17,   3,   1,  20, acGUI_FontFontSong20_7535 } /* code 7535 */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_754C } /* code 754C */
  ,{  18,  17,   1,   1,  20, acGUI_FontFontSong20_76F4 } /* code 76F4 */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_793A } /* code 793A */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_79FB } /* code 79FB */
  ,{  18,  17,   1,   1,  20, acGUI_FontFontSong20_7F6E } /* code 7F6E */
  ,{  13,  18,   4,   1,  20, acGUI_FontFontSong20_81EA } /* code 81EA */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_85CF } /* code 85CF */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_884C } /* code 884C */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_8868 } /* code 8868 */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_89C8 } /* code 89C8 */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_89E6 } /* code 89E6 */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_8BBE } /* code 8BBE */
  ,{  18,  17,   1,   1,  20, acGUI_FontFontSong20_8FD0 } /* code 8FD0 */
  ,{  18,  17,   1,   1,  20, acGUI_FontFontSong20_8FDB } /* code 8FDB */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_91C7 } /* code 91C7 */
  ,{  18,  17,   1,   1,  20, acGUI_FontFontSong20_91CF } /* code 91CF */
  ,{  17,  18,   2,   1,  20, acGUI_FontFontSong20_9636 } /* code 9636 */
  ,{  17,  18,   2,   1,  20, acGUI_FontFontSong20_9690 } /* code 9690 */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_9762 } /* code 9762 */
  ,{  18,  18,   1,   1,  20, acGUI_FontFontSong20_9891 } /* code 9891 */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop56 = {
   0x9891 /* first character */
  ,0x9891 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[113] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop55 = {
   0x9762 /* first character */
  ,0x9762 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[112] /* address of first character */
  ,&GUI_FontFontSong20_Prop56 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop54 = {
   0x9690 /* first character */
  ,0x9690 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[111] /* address of first character */
  ,&GUI_FontFontSong20_Prop55 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop53 = {
   0x9636 /* first character */
  ,0x9636 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[110] /* address of first character */
  ,&GUI_FontFontSong20_Prop54 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop52 = {
   0x91CF /* first character */
  ,0x91CF /* last character  */
  ,&GUI_FontFontSong20_CharInfo[109] /* address of first character */
  ,&GUI_FontFontSong20_Prop53 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop51 = {
   0x91C7 /* first character */
  ,0x91C7 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[108] /* address of first character */
  ,&GUI_FontFontSong20_Prop52 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop50 = {
   0x8FDB /* first character */
  ,0x8FDB /* last character  */
  ,&GUI_FontFontSong20_CharInfo[107] /* address of first character */
  ,&GUI_FontFontSong20_Prop51 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop49 = {
   0x8FD0 /* first character */
  ,0x8FD0 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[106] /* address of first character */
  ,&GUI_FontFontSong20_Prop50 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop48 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_FontFontSong20_CharInfo[105] /* address of first character */
  ,&GUI_FontFontSong20_Prop49 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop47 = {
   0x89E6 /* first character */
  ,0x89E6 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[104] /* address of first character */
  ,&GUI_FontFontSong20_Prop48 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop46 = {
   0x89C8 /* first character */
  ,0x89C8 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[103] /* address of first character */
  ,&GUI_FontFontSong20_Prop47 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop45 = {
   0x8868 /* first character */
  ,0x8868 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[102] /* address of first character */
  ,&GUI_FontFontSong20_Prop46 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop44 = {
   0x884C /* first character */
  ,0x884C /* last character  */
  ,&GUI_FontFontSong20_CharInfo[101] /* address of first character */
  ,&GUI_FontFontSong20_Prop45 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop43 = {
   0x85CF /* first character */
  ,0x85CF /* last character  */
  ,&GUI_FontFontSong20_CharInfo[100] /* address of first character */
  ,&GUI_FontFontSong20_Prop44 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop42 = {
   0x81EA /* first character */
  ,0x81EA /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 99] /* address of first character */
  ,&GUI_FontFontSong20_Prop43 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop41 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 98] /* address of first character */
  ,&GUI_FontFontSong20_Prop42 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop40 = {
   0x79FB /* first character */
  ,0x79FB /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 97] /* address of first character */
  ,&GUI_FontFontSong20_Prop41 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop39 = {
   0x793A /* first character */
  ,0x793A /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 96] /* address of first character */
  ,&GUI_FontFontSong20_Prop40 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop38 = {
   0x76F4 /* first character */
  ,0x76F4 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 95] /* address of first character */
  ,&GUI_FontFontSong20_Prop39 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop37 = {
   0x754C /* first character */
  ,0x754C /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 94] /* address of first character */
  ,&GUI_FontFontSong20_Prop38 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop36 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 93] /* address of first character */
  ,&GUI_FontFontSong20_Prop37 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop35 = {
   0x7387 /* first character */
  ,0x7387 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 92] /* address of first character */
  ,&GUI_FontFontSong20_Prop36 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop34 = {
   0x72B6 /* first character */
  ,0x72B6 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 91] /* address of first character */
  ,&GUI_FontFontSong20_Prop35 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop33 = {
   0x6EE4 /* first character */
  ,0x6EE4 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 90] /* address of first character */
  ,&GUI_FontFontSong20_Prop34 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop32 = {
   0x6E38 /* first character */
  ,0x6E38 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 89] /* address of first character */
  ,&GUI_FontFontSong20_Prop33 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop31 = {
   0x6D4F /* first character */
  ,0x6D4F /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 88] /* address of first character */
  ,&GUI_FontFontSong20_Prop32 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop30 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 87] /* address of first character */
  ,&GUI_FontFontSong20_Prop31 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop29 = {
   0x6CE2 /* first character */
  ,0x6CE2 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 86] /* address of first character */
  ,&GUI_FontFontSong20_Prop30 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop28 = {
   0x6C34 /* first character */
  ,0x6C34 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 85] /* address of first character */
  ,&GUI_FontFontSong20_Prop29 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop27 = {
   0x6B65 /* first character */
  ,0x6B65 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 84] /* address of first character */
  ,&GUI_FontFontSong20_Prop28 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop26 = {
   0x6837 /* first character */
  ,0x6837 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 83] /* address of first character */
  ,&GUI_FontFontSong20_Prop27 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop25 = {
   0x6807 /* first character */
  ,0x6807 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 82] /* address of first character */
  ,&GUI_FontFontSong20_Prop26 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop24 = {
   0x6682 /* first character */
  ,0x6682 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 81] /* address of first character */
  ,&GUI_FontFontSong20_Prop25 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop23 = {
   0x663E /* first character */
  ,0x663E /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 80] /* address of first character */
  ,&GUI_FontFontSong20_Prop24 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop22 = {
   0x6570 /* first character */
  ,0x6570 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 79] /* address of first character */
  ,&GUI_FontFontSong20_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop21 = {
   0x63CF /* first character */
  ,0x63CF /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 78] /* address of first character */
  ,&GUI_FontFontSong20_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop20 = {
   0x626B /* first character */
  ,0x626B /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 77] /* address of first character */
  ,&GUI_FontFontSong20_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop19 = {
   0x6001 /* first character */
  ,0x6001 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 76] /* address of first character */
  ,&GUI_FontFontSong20_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop18 = {
   0x5F62 /* first character */
  ,0x5F62 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 75] /* address of first character */
  ,&GUI_FontFontSong20_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop17 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 74] /* address of first character */
  ,&GUI_FontFontSong20_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop16 = {
   0x5E73 /* first character */
  ,0x5E73 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 73] /* address of first character */
  ,&GUI_FontFontSong20_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop15 = {
   0x5E45 /* first character */
  ,0x5E45 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 72] /* address of first character */
  ,&GUI_FontFontSong20_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop14 = {
   0x5B66 /* first character */
  ,0x5B66 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 71] /* address of first character */
  ,&GUI_FontFontSong20_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop13 = {
   0x5782 /* first character */
  ,0x5782 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 70] /* address of first character */
  ,&GUI_FontFontSong20_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop12 = {
   0x5668 /* first character */
  ,0x5668 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 69] /* address of first character */
  ,&GUI_FontFontSong20_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop11 = {
   0x53D1 /* first character */
  ,0x53D1 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 68] /* address of first character */
  ,&GUI_FontFontSong20_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop10 = {
   0x53C2 /* first character */
  ,0x53C2 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 67] /* address of first character */
  ,&GUI_FontFontSong20_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop9 = {
   0x538B /* first character */
  ,0x538B /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 66] /* address of first character */
  ,&GUI_FontFontSong20_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop8 = {
   0x52A8 /* first character */
  ,0x52A8 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 65] /* address of first character */
  ,&GUI_FontFontSong20_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop7 = {
   0x505C /* first character */
  ,0x505C /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 64] /* address of first character */
  ,&GUI_FontFontSong20_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop6 = {
   0x4F4D /* first character */
  ,0x4F4D /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 63] /* address of first character */
  ,&GUI_FontFontSong20_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop5 = {
   0x0079 /* first character */
  ,0x007A /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 61] /* address of first character */
  ,&GUI_FontFontSong20_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop4 = {
   0x0061 /* first character */
  ,0x0077 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 38] /* address of first character */
  ,&GUI_FontFontSong20_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop3 = {
   0x0041 /* first character */
  ,0x005A /* last character  */
  ,&GUI_FontFontSong20_CharInfo[ 12] /* address of first character */
  ,&GUI_FontFontSong20_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop2 = {
   0x002F /* first character */
  ,0x0039 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[  1] /* address of first character */
  ,&GUI_FontFontSong20_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSong20_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontFontSong20_CharInfo[  0] /* address of first character */
  ,&GUI_FontFontSong20_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFontSong20 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,20 /* height of font  */
  ,20 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFontSong20_Prop1}
  ,17 /* Baseline */
  ,9 /* Height of lowercase characters */
  ,13 /* Height of capital characters */
};

