/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.40                      *
*        Compiled Mar 17 2017, 15:34:36                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: FontSong16.c                                          *
* Font:        ËÎÌå                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: D:\¿ÎÉè\emwin×ÖÌå\1.txt                         *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFontSong16;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_0020[ 16] = { /* code 0020, SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_0030[ 16] = { /* code 0030, DIGIT ZERO */
  ________,
  ________,
  ________,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_0032[ 16] = { /* code 0032, DIGIT TWO */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X____X_,
  _XXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_0034[ 16] = { /* code 0034, DIGIT FOUR */
  ________,
  ________,
  ________,
  _____X__,
  ____XX__,
  ____XX__,
  ___X_X__,
  __X__X__,
  __X__X__,
  _X___X__,
  _XXXXXXX,
  _____X__,
  _____X__,
  ___XXXXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_0038[ 16] = { /* code 0038, DIGIT EIGHT */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_0041[ 16] = { /* code 0041, LATIN CAPITAL LETTER A */
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___XX___,
  __X_X___,
  __X_X___,
  __X__X__,
  __XXXX__,
  _X___X__,
  _X____X_,
  _X____X_,
  XXX__XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_0042[ 16] = { /* code 0042, LATIN CAPITAL LETTER B */
  ________,
  ________,
  ________,
  XXXXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _XXXX___,
  _X___X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_0046[ 16] = { /* code 0046, LATIN CAPITAL LETTER F */
  ________,
  ________,
  ________,
  XXXXXX__,
  _X____X_,
  _X__X___,
  _X__X___,
  _XXXX___,
  _X__X___,
  _X__X___,
  _X______,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_0054[ 16] = { /* code 0054, LATIN CAPITAL LETTER T */
  ________,
  ________,
  ________,
  XXXXXXX_,
  X__X__X_,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_0058[ 16] = { /* code 0058, LATIN CAPITAL LETTER X */
  ________,
  ________,
  ________,
  XXX__XXX,
  _X____X_,
  __X__X__,
  __X__X__,
  ___XX___,
  ___XX___,
  ___XX___,
  __X__X__,
  __X__X__,
  _X____X_,
  XXX__XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_0059[ 16] = { /* code 0059, LATIN CAPITAL LETTER Y */
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  _X___X__,
  __X_X___,
  __X_X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __XXX___,
  ________,
  ________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_4F4D[ 32] = { /* code 4F4D */
  ____X___,X_______,
  ____X___,_X______,
  ____X___,_X______,
  ___X____,________,
  ___X_XXX,XXXXXX__,
  __XX____,________,
  __XX____,____X___,
  _X_X__X_,____X___,
  X__X__X_,____X___,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X___X,__X_____,
  ___X____,__X_____,
  ___XXXXX,XXXXXXX_,
  ___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_52A8[ 32] = { /* code 52A8 */
  ________,_X______,
  ________,_X______,
  _XXXXX__,_X______,
  ________,_X______,
  _______X,XXXXXX__,
  ________,_X___X__,
  XXXXXXX_,_X___X__,
  __X_____,_X___X__,
  __X_____,_X___X__,
  __X_____,X____X__,
  _X__X___,X____X__,
  _X___X__,X____X__,
  XXXXXX_X,_____X__,
  _X___X_X,_____X__,
  ______X_,__X_X___,
  _____X__,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_53C2[ 32] = { /* code 53C2 */
  ______X_,________,
  _____X__,_X______,
  ____X___,__X_____,
  ___XXXXX,XXXX____,
  ______X_,________,
  _XXXXXXX,XXXXXX__,
  ____X___,__X_____,
  ___X____,X__X____,
  __X___XX,____X___,
  XX__XX__,_X___XX_,
  _______X,X_______,
  _____XX_,___X____,
  ___XX___,__X_____,
  ________,XX______,
  _____XXX,________,
  _XXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_53D1[ 32] = { /* code 53D1 */
  _______X,________,
  ___X___X,___X____,
  ___X___X,____X___,
  __X___X_,________,
  __XXXXXX,XXXXXX__,
  ______X_,________,
  _____X__,________,
  _____XXX,XXXXX___,
  ____X_X_,____X___,
  ____X__X,____X___,
  ___X___X,___X____,
  ___X____,X_X_____,
  __X_____,_X______,
  _X______,X_X_____,
  ______XX,___XX___,
  ___XXX__,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_5668[ 32] = { /* code 5668 */
  ________,________,
  __XXXXX_,_XXXXX__,
  __X___X_,_X___X__,
  __X___X_,_X___X__,
  __XXXXX_,_XXXXX__,
  _______X,__X_____,
  _______X,___X____,
  XXXXXXXX,XXXXXXX_,
  ______X_,X_______,
  ____XX__,_XX_____,
  __XX____,___XX___,
  XX______,_____XX_,
  __XXXXX_,_XXXXX__,
  __X___X_,_X___X__,
  __X___X_,_X___X__,
  __XXXXX_,_XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_5782[ 32] = { /* code 5782 */
  ________,___X____,
  ________,XXXXX___,
  __XXXXXX,________,
  _______X,________,
  _______X,________,
  _XXXXXXX,XXXXXX__,
  ____X__X,__X_____,
  ____X__X,__X_____,
  XXXXXXXX,XXXXXXX_,
  ____X__X,__X_____,
  ____X__X,__X_____,
  _XXXXXXX,XXXXXX__,
  _______X,________,
  _______X,________,
  __XXXXXX,XXXXX___,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_5B66[ 32] = { /* code 5B66 */
  __X___X_,____X___,
  ___X___X,____X___,
  ___X___X,___X____,
  ________,__X_____,
  _XXXXXXX,XXXXXXX_,
  _X______,______X_,
  X_______,_____X__,
  ___XXXXX,XXX_____,
  ________,_X______,
  _______X,X_______,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  _______X,________,
  _____X_X,________,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_5E73[ 32] = { /* code 5E73 */
  ________,________,
  _XXXXXXX,XXXXXX__,
  _______X,________,
  _______X,________,
  ___X___X,___X____,
  ____X__X,___X____,
  ____X__X,__X_____,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_5F62[ 32] = { /* code 5F62 */
  ________,________,
  _XXXXXXX,X____X__,
  ___X__X_,_____X__,
  ___X__X_,____X___,
  ___X__X_,___X____,
  ___X__X_,__X___X_,
  ___X__X_,______X_,
  XXXXXXXX,XX___X__,
  ___X__X_,____X___,
  ___X__X_,___X____,
  ___X__X_,__X___X_,
  ___X__X_,______X_,
  __X___X_,_____X__,
  __X___X_,____X___,
  _X____X_,___X____,
  X_____X_,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_6570[ 32] = { /* code 6570 */
  ____X___,__X_____,
  _X__X__X,__X_____,
  __X_X_X_,__X_____,
  ____X___,__XXXXX_,
  XXXXXXXX,_X___X__,
  __X_X_X_,_X___X__,
  _X__X__X,_X___X__,
  X___X___,X_X__X__,
  ___X____,__X_X___,
  XXXXXXX_,__X_X___,
  __X___X_,___X____,
  _X____X_,___X____,
  _XX__X__,__X_X___,
  ___XX___,__X_X___,
  __XX_X__,_X___X__,
  XX____X_,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_663E[ 32] = { /* code 663E */
  ________,________,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  _____X__,_X______,
  _X___X__,_X___X__,
  __X__X__,_X___X__,
  ___X_X__,_X__X___,
  ___X_X__,_X_X____,
  _____X__,_X______,
  XXXXXXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_6807[ 32] = { /* code 6807 */
  ___X____,________,
  ___X___X,XXXXXX__,
  ___X____,________,
  ___X____,________,
  XXXXXX__,________,
  ___X__XX,XXXXXXX_,
  __XX____,__X_____,
  __XXX___,__X_____,
  _X_X_X_X,__X_X___,
  _X_X_X_X,__X__X__,
  X__X__X_,__X__X__,
  ___X__X_,__X___X_,
  ___X_X__,__X___X_,
  ___X____,__X_____,
  ___X____,X_X_____,
  ___X____,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_6837[ 32] = { /* code 6837 */
  ___X___X,_____X__,
  ___X____,X____X__,
  ___X____,X___X___,
  ___X____,________,
  XXXXX_XX,XXXXXXX_,
  ___X____,__X_____,
  __XX____,__X_____,
  __XXX__X,XXXXXX__,
  _X_X_X__,__X_____,
  _X_X____,__X_____,
  X__X__XX,XXXXXXX_,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_6B65[ 32] = { /* code 6B65 */
  _______X,________,
  _______X,________,
  ___X___X,XXXXX___,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  ___X___X,____X___,
  ___X___X,___X____,
  __X____X,__X_____,
  _X______,XX______,
  ______XX,________,
  ___XXX__,________,
  XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_6C34[ 32] = { /* code 6C34 */
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,____X___,
  _______X,____X___,
  _XXXXX_X,X__X____,
  _____X_X,X_X_____,
  ____X__X,_X______,
  ____X__X,_X______,
  ___X___X,__X_____,
  ___X___X,___X____,
  __X____X,____X___,
  _X_____X,_____XX_,
  X______X,________,
  _____X_X,________,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_6CE2[ 32] = { /* code 6CE2 */
  ________,__X_____,
  __X_____,__X_____,
  ___X____,__X_____,
  ___X__XX,XXXXXXX_,
  X_____X_,__X___X_,
  _X____X_,__X__X__,
  _X__X_X_,__X_____,
  ____X_XX,XXXXXX__,
  ___X__X_,X____X__,
  ___X__X_,X___X___,
  XXX___X_,_X__X___,
  __X___X_,_X_X____,
  __X___X_,__X_____,
  __X__X__,_X_X____,
  __X__X__,X___X___,
  ____X__X,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_6D4B[ 32] = { /* code 6D4B */
  ________,_____X__,
  __X__XXX,XX___X__,
  ___X_X__,_X___X__,
  ___X_X__,_X_X_X__,
  X____X_X,_X_X_X__,
  _X___X_X,_X_X_X__,
  _X___X_X,_X_X_X__,
  ___X_X_X,_X_X_X__,
  ___X_X_X,_X_X_X__,
  __X__X_X,_X_X_X__,
  XXX__X_X,_X_X_X__,
  __X____X,_____X__,
  __X___X_,X____X__,
  __X___X_,_X___X__,
  __X__X__,___X_X__,
  ____X___,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_6D4F[ 32] = { /* code 6D4F */
  ______X_,_____X__,
  _X_____X,_____X__,
  __X____X,_____X__,
  __X_XXXX,XXX__X__,
  ________,X__X_X__,
  X____X__,X__X_X__,
  _X____X_,X__X_X__,
  _X_X__X_,X__X_X__,
  ___X___X,___X_X__,
  __X____X,___X_X__,
  XXX___X_,X__X_X__,
  __X___X_,X__X_X__,
  __X__X__,_X___X__,
  __X_X___,_X___X__,
  __XX____,___X_X__,
  ________,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_6E38[ 32] = { /* code 6E38 */
  ______X_,___X____,
  __X____X,___X____,
  ___X___X,___X____,
  ___X_XXX,X_XXXXX_,
  X_____X_,__X_____,
  _X____X_,_X______,
  _X____XX,X_XXXX__,
  ___X__X_,X____X__,
  ___X__X_,X___X___,
  __X___X_,X___X___,
  XXX___X_,X_XXXXX_,
  __X___X_,X___X___,
  __X__X__,X___X___,
  __X__X__,X___X___,
  __X_X__X,X_X_X___,
  ___X____,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_6EE4[ 32] = { /* code 6EE4 */
  ________,_X______,
  __X_____,_XXXXX__,
  ___X____,_X______,
  ___X_XXX,XXXXXXX_,
  X____X__,_X____X_,
  _X___X__,_XXX____,
  _X___XXX,XX___X__,
  ___X_X__,_X___X__,
  ___X_X__,__XXXX__,
  __X__X__,__X_____,
  XXX__X__,___X____,
  __X__X__,_X_X_X__,
  __X__X_X,_X____X_,
  __X_X__X,_X____X_,
  __X_X__X,_X__X_X_,
  ___X__X_,__XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_7387[ 32] = { /* code 7387 */
  ______X_,________,
  _______X,________,
  _XXXXXXX,XXXXXX__,
  ______X_,________,
  _X___X__,_X___X__,
  __X_XXXX,X___X___,
  ___X___X,___X____,
  __X___X_,_X__X___,
  _X__XXXX,XXX__X__,
  ________,__X_____,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_76F4[ 32] = { /* code 76F4 */
  _______X,________,
  _______X,________,
  _XXXXXXX,XXXXXX__,
  _______X,________,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  XXXXXXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_793A[ 32] = { /* code 793A */
  ________,________,
  __XXXXXX,XXXXX___,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  ___X___X,___X____,
  ___X___X,____X___,
  __X____X,_____X__,
  _X_____X,______X_,
  X______X,______X_,
  _____X_X,________,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_79FB[ 32] = { /* code 79FB */
  ____X___,__X_____,
  ___XXX__,__X_____,
  XXXX____,_XXXXX__,
  ___X____,X____X__,
  ___X___X,_X__X___,
  XXXXXX__,__XX____,
  ___X____,__X_____,
  __XX____,_X__X___,
  __XXX__X,X__X____,
  _X_X_X__,__XXXXX_,
  _X_X_X__,_X____X_,
  X__X___X,X_X__X__,
  ___X____,___XX___,
  ___X____,___X____,
  ___X____,_XX_____,
  ___X___X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_7F6E[ 32] = { /* code 7F6E */
  _XXXXXXX,XXXXXX__,
  _X___X__,_X___X__,
  _XXXXXXX,XXXXXX__,
  _______X,________,
  _XXXXXXX,XXXXXX__,
  _______X,________,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  XXXXXXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_81EA[ 32] = { /* code 81EA */
  _______X,________,
  ______X_,________,
  _____X__,________,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_85CF[ 32] = { /* code 85CF */
  _____X__,_X______,
  XXXXXXXX,XXXXXXX_,
  _____X__,_X__X___,
  ________,__X__X__,
  ___XXXXX,XXXXXXX_,
  _X_X____,__X_____,
  _X_X_XXX,X_X_____,
  _XXX_X_X,__X__X__,
  ___X_XXX,X_X__X__,
  XXXX_X__,X_X_X___,
  _X_X_XXX,X_X_X___,
  _X_X_X_X,___X____,
  X__X_X_X,___X__X_,
  __X__XXX,X_X_X_X_,
  __X_____,_X___XX_,
  _X______,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_884C[ 32] = { /* code 884C */
  ____X___,________,
  ____X__X,XXXXXX__,
  ___X____,________,
  __X_____,________,
  _X__X___,________,
  ____X___,________,
  ___X__XX,XXXXXXX_,
  __XX____,__X_____,
  _X_X____,__X_____,
  X__X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,X_X_____,
  ___X____,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_89C8[ 32] = { /* code 89C8 */
  _____X__,_X______,
  __X__X__,_X______,
  __X__X__,_XXXXX__,
  __X__X__,X__X____,
  __X__X_X,____X___,
  _____X__,________,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X__X_,X__X____,
  ______X_,X_______,
  _____X__,X____X__,
  ___XX___,X____X__,
  _XX_____,_XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_89E6[ 32] = { /* code 89E6 */
  __X_____,__X_____,
  __X_____,__X_____,
  _XXXX___,__X_____,
  _X__X__X,XXXXXX__,
  X__X___X,__X__X__,
  _XXXXX_X,__X__X__,
  _X_X_X_X,__X__X__,
  _X_X_X_X,__X__X__,
  _XXXXX_X,XXXXXX__,
  _X_X_X_X,__X__X__,
  _X_X_X__,__X_____,
  _XXXXX__,__X_X___,
  _X_X_X__,__X__X__,
  _X_X_XXX,XXXXXXX_,
  _X___X_X,______X_,
  X___XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_8BBE[ 32] = { /* code 8BBE */
  ________,________,
  __X____X,XXXX____,
  ___X___X,___X____,
  ___X___X,___X____,
  _______X,___X____,
  ______X_,____XXX_,
  XXXX_X__,________,
  ___X__XX,XXXXX___,
  ___X___X,____X___,
  ___X___X,___X____,
  ___X____,X__X____,
  ___X_X__,X_X_____,
  ___XX___,_X______,
  ___X____,X_X_____,
  ______XX,___XX___,
  ____XX__,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_8FD0[ 32] = { /* code 8FD0 */
  ________,________,
  __X___XX,XXXXX___,
  ___X____,________,
  ___X____,________,
  ________,________,
  _____XXX,XXXXXX__,
  XXXX____,_X______,
  ___X____,X_______,
  ___X___X,___X____,
  ___X__X_,____X___,
  ___X_XXX,XXXXXX__,
  ___X__X_,_____X__,
  ___X____,________,
  __X_X___,________,
  _X___XXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_8FDB[ 32] = { /* code 8FDB */
  ________,X__X____,
  __X_____,X__X____,
  ___X____,X__X____,
  ___X__XX,XXXXXX__,
  ________,X__X____,
  ________,X__X____,
  XXXX____,X__X____,
  ___X_XXX,XXXXXXX_,
  ___X____,X__X____,
  ___X____,X__X____,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X__X_,___X____,
  __X_X___,________,
  _X___XXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_91C7[ 32] = { /* code 91C7 */
  ________,___X____,
  ________,XXXXX___,
  __XXXXXX,________,
  ______X_,________,
  ___X___X,___X____,
  ____X__X,___X____,
  ____X___,__X_____,
  _______X,________,
  _XXXXXXX,XXXXXX__,
  ______XX,X_______,
  _____X_X,_X______,
  ____X__X,__X_____,
  ___X___X,___X____,
  __X____X,____X___,
  XX_____X,_____XX_,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_91CF[ 32] = { /* code 91CF */
  ________,________,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  XXXXXXXX,XXXXXXX_,
  ________,________,
  ___XXXXX,XXXX____,
  ___X___X,___X____,
  ___XXXXX,XXXX____,
  ___X___X,___X____,
  ___XXXXX,XXXX____,
  _______X,________,
  ___XXXXX,XXXX____,
  _______X,________,
  _XXXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_9636[ 32] = { /* code 9636 */
  ________,__X_____,
  _XXXXX__,__X_____,
  _X___X__,_X_X____,
  _X__X___,_X_X____,
  _X__X___,X___X___,
  _X_X___X,_____X__,
  _X__X_X_,______X_,
  _X__X___,X___X___,
  _X___X__,X___X___,
  _X___X__,X___X___,
  _X___X__,X___X___,
  _XX_X___,X___X___,
  _X_X____,X___X___,
  _X_____X,____X___,
  _X_____X,____X___,
  _X____X_,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_9690[ 32] = { /* code 9690 */
  ________,X_______,
  _XXXX___,X_______,
  _X__X__X,XXXXX___,
  _X__X_X_,____X___,
  _X_X_X__,___X____,
  _X_X__XX,XXXXXX__,
  _XX_____,_____X__,
  _X_X___X,XXXXXX__,
  _X__X___,_____X__,
  _X__X_XX,XXXXXX__,
  _X__X___,_____X__,
  _XX_X___,_X______,
  _X_X___X,__X__X__,
  _X___X_X,__X_X_X_,
  _X___X_X,____X_X_,
  _X__X___,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_9891[ 32] = { /* code 9891 */
  ___X____,________,
  ___X___X,XXXXXXX_,
  _X_X____,__X_____,
  _X_XXX__,_X______,
  _X_X___X,XXXXXX__,
  _X_X___X,_____X__,
  XXXXXXXX,__X__X__,
  _______X,__X__X__,
  ___X___X,__X__X__,
  _X_X_X_X,__X__X__,
  _X_X_X_X,__X__X__,
  _X_X_X_X,_X___X__,
  X____X__,_X_X____,
  ____X___,X___X___,
  __XX___X,_____X__,
  XX____X_,______X_};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontFontSong16_CharInfo[49] = {
   {   8,   8,  1, acGUI_FontFontSong16_0020 } /* code 0020 */
  ,{   8,   8,  1, acGUI_FontFontSong16_0030 } /* code 0030 */
  ,{   8,   8,  1, acGUI_FontFontSong16_0032 } /* code 0032 */
  ,{   8,   8,  1, acGUI_FontFontSong16_0034 } /* code 0034 */
  ,{   8,   8,  1, acGUI_FontFontSong16_0038 } /* code 0038 */
  ,{   8,   8,  1, acGUI_FontFontSong16_0041 } /* code 0041 */
  ,{   8,   8,  1, acGUI_FontFontSong16_0042 } /* code 0042 */
  ,{   8,   8,  1, acGUI_FontFontSong16_0046 } /* code 0046 */
  ,{   8,   8,  1, acGUI_FontFontSong16_0054 } /* code 0054 */
  ,{   8,   8,  1, acGUI_FontFontSong16_0058 } /* code 0058 */
  ,{   8,   8,  1, acGUI_FontFontSong16_0059 } /* code 0059 */
  ,{  16,  16,  2, acGUI_FontFontSong16_4F4D } /* code 4F4D */
  ,{  16,  16,  2, acGUI_FontFontSong16_52A8 } /* code 52A8 */
  ,{  16,  16,  2, acGUI_FontFontSong16_53C2 } /* code 53C2 */
  ,{  16,  16,  2, acGUI_FontFontSong16_53D1 } /* code 53D1 */
  ,{  16,  16,  2, acGUI_FontFontSong16_5668 } /* code 5668 */
  ,{  16,  16,  2, acGUI_FontFontSong16_5782 } /* code 5782 */
  ,{  16,  16,  2, acGUI_FontFontSong16_5B66 } /* code 5B66 */
  ,{  16,  16,  2, acGUI_FontFontSong16_5E73 } /* code 5E73 */
  ,{  16,  16,  2, acGUI_FontFontSong16_5F62 } /* code 5F62 */
  ,{  16,  16,  2, acGUI_FontFontSong16_6570 } /* code 6570 */
  ,{  16,  16,  2, acGUI_FontFontSong16_663E } /* code 663E */
  ,{  16,  16,  2, acGUI_FontFontSong16_6807 } /* code 6807 */
  ,{  16,  16,  2, acGUI_FontFontSong16_6837 } /* code 6837 */
  ,{  16,  16,  2, acGUI_FontFontSong16_6B65 } /* code 6B65 */
  ,{  16,  16,  2, acGUI_FontFontSong16_6C34 } /* code 6C34 */
  ,{  16,  16,  2, acGUI_FontFontSong16_6CE2 } /* code 6CE2 */
  ,{  16,  16,  2, acGUI_FontFontSong16_6D4B } /* code 6D4B */
  ,{  16,  16,  2, acGUI_FontFontSong16_6D4F } /* code 6D4F */
  ,{  16,  16,  2, acGUI_FontFontSong16_6E38 } /* code 6E38 */
  ,{  16,  16,  2, acGUI_FontFontSong16_6EE4 } /* code 6EE4 */
  ,{  16,  16,  2, acGUI_FontFontSong16_7387 } /* code 7387 */
  ,{  16,  16,  2, acGUI_FontFontSong16_76F4 } /* code 76F4 */
  ,{  16,  16,  2, acGUI_FontFontSong16_793A } /* code 793A */
  ,{  16,  16,  2, acGUI_FontFontSong16_79FB } /* code 79FB */
  ,{  16,  16,  2, acGUI_FontFontSong16_7F6E } /* code 7F6E */
  ,{  16,  16,  2, acGUI_FontFontSong16_81EA } /* code 81EA */
  ,{  16,  16,  2, acGUI_FontFontSong16_85CF } /* code 85CF */
  ,{  16,  16,  2, acGUI_FontFontSong16_884C } /* code 884C */
  ,{  16,  16,  2, acGUI_FontFontSong16_89C8 } /* code 89C8 */
  ,{  16,  16,  2, acGUI_FontFontSong16_89E6 } /* code 89E6 */
  ,{  16,  16,  2, acGUI_FontFontSong16_8BBE } /* code 8BBE */
  ,{  16,  16,  2, acGUI_FontFontSong16_8FD0 } /* code 8FD0 */
  ,{  16,  16,  2, acGUI_FontFontSong16_8FDB } /* code 8FDB */
  ,{  16,  16,  2, acGUI_FontFontSong16_91C7 } /* code 91C7 */
  ,{  16,  16,  2, acGUI_FontFontSong16_91CF } /* code 91CF */
  ,{  16,  16,  2, acGUI_FontFontSong16_9636 } /* code 9636 */
  ,{  16,  16,  2, acGUI_FontFontSong16_9690 } /* code 9690 */
  ,{  16,  16,  2, acGUI_FontFontSong16_9891 } /* code 9891 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop47 = {
   0x9891 /* first character */
  ,0x9891 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 48] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop46 = {
   0x9690 /* first character */
  ,0x9690 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 47] /* address of first character */
  ,&GUI_FontFontSong16_Prop47 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop45 = {
   0x9636 /* first character */
  ,0x9636 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 46] /* address of first character */
  ,&GUI_FontFontSong16_Prop46 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop44 = {
   0x91CF /* first character */
  ,0x91CF /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 45] /* address of first character */
  ,&GUI_FontFontSong16_Prop45 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop43 = {
   0x91C7 /* first character */
  ,0x91C7 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 44] /* address of first character */
  ,&GUI_FontFontSong16_Prop44 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop42 = {
   0x8FDB /* first character */
  ,0x8FDB /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 43] /* address of first character */
  ,&GUI_FontFontSong16_Prop43 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop41 = {
   0x8FD0 /* first character */
  ,0x8FD0 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 42] /* address of first character */
  ,&GUI_FontFontSong16_Prop42 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop40 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 41] /* address of first character */
  ,&GUI_FontFontSong16_Prop41 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop39 = {
   0x89E6 /* first character */
  ,0x89E6 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 40] /* address of first character */
  ,&GUI_FontFontSong16_Prop40 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop38 = {
   0x89C8 /* first character */
  ,0x89C8 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 39] /* address of first character */
  ,&GUI_FontFontSong16_Prop39 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop37 = {
   0x884C /* first character */
  ,0x884C /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 38] /* address of first character */
  ,&GUI_FontFontSong16_Prop38 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop36 = {
   0x85CF /* first character */
  ,0x85CF /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 37] /* address of first character */
  ,&GUI_FontFontSong16_Prop37 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop35 = {
   0x81EA /* first character */
  ,0x81EA /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 36] /* address of first character */
  ,&GUI_FontFontSong16_Prop36 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop34 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 35] /* address of first character */
  ,&GUI_FontFontSong16_Prop35 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop33 = {
   0x79FB /* first character */
  ,0x79FB /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 34] /* address of first character */
  ,&GUI_FontFontSong16_Prop34 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop32 = {
   0x793A /* first character */
  ,0x793A /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 33] /* address of first character */
  ,&GUI_FontFontSong16_Prop33 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop31 = {
   0x76F4 /* first character */
  ,0x76F4 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 32] /* address of first character */
  ,&GUI_FontFontSong16_Prop32 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop30 = {
   0x7387 /* first character */
  ,0x7387 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 31] /* address of first character */
  ,&GUI_FontFontSong16_Prop31 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop29 = {
   0x6EE4 /* first character */
  ,0x6EE4 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 30] /* address of first character */
  ,&GUI_FontFontSong16_Prop30 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop28 = {
   0x6E38 /* first character */
  ,0x6E38 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 29] /* address of first character */
  ,&GUI_FontFontSong16_Prop29 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop27 = {
   0x6D4F /* first character */
  ,0x6D4F /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 28] /* address of first character */
  ,&GUI_FontFontSong16_Prop28 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop26 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 27] /* address of first character */
  ,&GUI_FontFontSong16_Prop27 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop25 = {
   0x6CE2 /* first character */
  ,0x6CE2 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 26] /* address of first character */
  ,&GUI_FontFontSong16_Prop26 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop24 = {
   0x6C34 /* first character */
  ,0x6C34 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 25] /* address of first character */
  ,&GUI_FontFontSong16_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop23 = {
   0x6B65 /* first character */
  ,0x6B65 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 24] /* address of first character */
  ,&GUI_FontFontSong16_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop22 = {
   0x6837 /* first character */
  ,0x6837 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 23] /* address of first character */
  ,&GUI_FontFontSong16_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop21 = {
   0x6807 /* first character */
  ,0x6807 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 22] /* address of first character */
  ,&GUI_FontFontSong16_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop20 = {
   0x663E /* first character */
  ,0x663E /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 21] /* address of first character */
  ,&GUI_FontFontSong16_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop19 = {
   0x6570 /* first character */
  ,0x6570 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 20] /* address of first character */
  ,&GUI_FontFontSong16_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop18 = {
   0x5F62 /* first character */
  ,0x5F62 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 19] /* address of first character */
  ,&GUI_FontFontSong16_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop17 = {
   0x5E73 /* first character */
  ,0x5E73 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 18] /* address of first character */
  ,&GUI_FontFontSong16_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop16 = {
   0x5B66 /* first character */
  ,0x5B66 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 17] /* address of first character */
  ,&GUI_FontFontSong16_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop15 = {
   0x5782 /* first character */
  ,0x5782 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 16] /* address of first character */
  ,&GUI_FontFontSong16_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop14 = {
   0x5668 /* first character */
  ,0x5668 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 15] /* address of first character */
  ,&GUI_FontFontSong16_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop13 = {
   0x53D1 /* first character */
  ,0x53D1 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 14] /* address of first character */
  ,&GUI_FontFontSong16_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop12 = {
   0x53C2 /* first character */
  ,0x53C2 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 13] /* address of first character */
  ,&GUI_FontFontSong16_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop11 = {
   0x52A8 /* first character */
  ,0x52A8 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 12] /* address of first character */
  ,&GUI_FontFontSong16_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop10 = {
   0x4F4D /* first character */
  ,0x4F4D /* last character  */
  ,&GUI_FontFontSong16_CharInfo[ 11] /* address of first character */
  ,&GUI_FontFontSong16_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop9 = {
   0x0058 /* first character */
  ,0x0059 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[  9] /* address of first character */
  ,&GUI_FontFontSong16_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop8 = {
   0x0054 /* first character */
  ,0x0054 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[  8] /* address of first character */
  ,&GUI_FontFontSong16_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop7 = {
   0x0046 /* first character */
  ,0x0046 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[  7] /* address of first character */
  ,&GUI_FontFontSong16_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop6 = {
   0x0041 /* first character */
  ,0x0042 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[  5] /* address of first character */
  ,&GUI_FontFontSong16_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop5 = {
   0x0038 /* first character */
  ,0x0038 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[  4] /* address of first character */
  ,&GUI_FontFontSong16_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop4 = {
   0x0034 /* first character */
  ,0x0034 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[  3] /* address of first character */
  ,&GUI_FontFontSong16_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop3 = {
   0x0032 /* first character */
  ,0x0032 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[  2] /* address of first character */
  ,&GUI_FontFontSong16_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop2 = {
   0x0030 /* first character */
  ,0x0030 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[  1] /* address of first character */
  ,&GUI_FontFontSong16_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[  0] /* address of first character */
  ,&GUI_FontFontSong16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFontSong16 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFontSong16_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

